### ISSUE TITLE
Cannot send payment if balance is lower than payment value

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#100]
Assume there is an account `issuer` with a balance of 0 and a minimum allowed balance `-infinity`. If I try to send a payment, there is an error saying "Sending amount should be less than your balance".

Apparently, the validation checks if the payment value is smaller than the current balance, without considering the minimum balance.

**Comment by vhpoet** [comment]
Yep, that's a bug currently. The way it works is it checks if the account is the admin and disables the minimum amount validation, so it will work if the issuer and admin are the same.
