### ISSUE TITLE
connector - different currency ledgers

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#102]
(not sure if this is an issue or a config problem on my side)

So... I (GBP) am connected to another ledger (USD) and would like to act as a connector an provide liquidity between both currencies.
Everything seems to be setup correctly (unless I am missing something), but I get the following error when trying to convert GBP to USD (it should default to fixerio?)...

`[api] Error: Got empty quote response from the connector`
`[api]     at client.connect.then.then.then (/home/javi/ilp-kit/node_modules/ilp/src/lib/sender.js:55:17)`
`[api] 2016-12-07T18:56:08.736Z error-handler WARN Not Found: No quote for a specified destination/amount has been found`
`[api] 2016-12-07T18:56:08.740Z http INFO   --> POST /payments/quote 404 11s -`

`CONNECTOR_ENABLE` is set to true and `CONNECTOR_LEDGERS` configured (I am able to see accounts from the other ledger on mine).

Any ideas?

**Comment by sharafian** [comment]
What logs are being produced by the ledger and the connector at that time? That `[api]` message indicated that the connector gave no response to a ledger message. It could be because the connector lost its connection to the ledger.

I was getting a similar error, but it was fixed when I upgraded my ledger version to 19.3.0.

**Comment by elmurci** [comment]
My bad guys,

The connector was not able to authenticate in the ledger on start up.

`[connector] 2016-12-08T20:58:48.173Z connector:app error Error: Unable to get auth token from ledger`
`[connector]     at FiveBellsLedger._connect (/home/javi/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:210:27)`
`[connector]     at next (native)`
`[connector]     at onFulfilled (/home/javi/ilp-kit/node_modules/co/index.js:65:19)`
`[connector]     at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by vhpoet** [comment]
@elmurci Did you not have a connector account? Commits posted to [this](https://github.com/interledgerjs/ilp-kit/issues/103) issue will automatically create and fund the connector account.

**Comment by elmurci** [comment]
Yeah, I had one but forgot to update the password in env.list with the good one (I had the one generated by default by the wizard).
Thanks @vhpoet !
