### ISSUE TITLE
Automatically create the connector account on the ledger

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#103]
When you configure the `ilp-kit` it asks you for a connector username and password. However when you run it, the connector complains that the user does not exist.

It seems like a very bad experience to ask the user for a username and password, then require them to run the `ilp-kit`, create the connector user, kill the `ilp-kit`, and run it again.

It would be better if the `ilp-kit` would automatically create the connector user from the `CONNECTOR_LEDGERS` field.

**Comment by vhpoet** [comment]
@emschwartz should admin automatically fund the connector account too?

**Comment by emschwartz** [comment]
It's a good question. For convenience I think that might be nice, though the amount would probably be something arbitrary (unless it were a configuration option). The issue I saw is that you walk through the configuration steps and then you end up with a setup that's useless until you do a couple more steps. It would be nice if at the end of the configuration flow you could just start up the kit and go.
