### ISSUE TITLE
Rebuilding modules

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-kit#104]
On some machines, modules have to be rebuilt (they are not built during`npm install` or during `npm run build`, for some reason).

The modules that this typically happens for are:

- `lwip`
- `sqlite3`
- `node-sass`
- `sodium-prebuilt`

**Comment by emschwartz** [comment]
Still having this issue

**Comment by adrianhopebailie** [comment]
I had some success on OSX by first making sure that the necessary build tools were installed:

  `$ brew install libtool autoconf automake`

p.s. Not sure there is a much benefit in using `sodium-prebuilt` over `sodium` which is more up to date too

**Comment by michielbdejong** [comment]
We now work around this issue by including rebuild as a postinstall step, see https://github.com/interledgerjs/ilp-kit/commit/dfc2aa31f46f11b39905df952ad6cc44e4ba50fc

**Comment by sharafian** [comment]
I still get the issue with `node-sass`, as of this morning. It doesn't happen every time I install, though.

**Comment by michielbdejong** [comment]
yeah, I also just saw:
```
9|api      | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
9|api      | Found bindings for the following environments:
9|api      |   - Linux 64-bit with Node.js 6.x
9|api      | This usually happens because your environment has changed since running `npm install`.
9|api      | Run `npm rebuild node-sass` to build the binding for your current environment.
```

in my logs. I did just update from node 6 to node 7 though.
