### ISSUE TITLE
Add simpler (or local) deploy option for testing and hackathons

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#107]
Most of the `ilp-kit` setup steps are related to getting set up on a server with nginx, Let's Encrypt, etc, rather than real ILP-related configuration.

It would be nice to be able to get an `ilp-kit` up and running much quicker, for example when we're at hackathons or other events pitching ILP to people.

Some of the options @sharafian, @dappelt and I talked about today for doing this are:

• Adding a [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button) button to the Readme (if we can get the configuration options to work -- we might need a kind of standalone site that would let you customize a couple of options like name and currency and then deploy it)
• Getting it to be a DigitalOcean [One-Click Install App](https://www.digitalocean.com/products/one-click-apps/) and maybe giving people $10 coupons
• Integrate [localtunnel](https://github.com/localtunnel/localtunnel) so that you could run the `ilp-kit` locally and expose it to the outside world (assuming you want to play with it for just the duration of an event)

Thoughts?

**Comment by emschwartz** [comment]
I'm partial to the localtunnel option because it would be nice to be able to use the kit without having to deal with running a server at all. And we could request the same subdomain so even if the connection to localtunnel.me flakes out you could restart with the same kit hostname (@sharafian)

**Comment by justmoon** [comment]
> I'm partial to the localtunnel option 

Agree. If the use case is hackathons, this seems by far the easiest option.

Does this require code changes or can this be accomplished by providing example commands in the README?

**Comment by sharafian** [comment]
Localtunnel's stability is a little bit spotty. It will occasionally shut down at random. It would be incredibly frustrating to have to edit your config file every time you run localtunnel.

However, Localtunnel can be started from [inside node](https://github.com/localtunnel/localtunnel#api). We could have an env variable inside of ILP Kit that creates a local tunnel and sets all public URIs to use it. Or we could have a special launcher that starts a localtunnel and assigns the correct env variables.

Another issue I can see with localtunnel is that the nginx/apache config might need to change every time the localtunnel URI changes.

**Comment by emschwartz** [comment]
Local tunnel lets you request a subdomain so it wouldn't necessarily need
to change every time you restart

**Comment by sharafian** [comment]
That's incredibly useful. I just tried, and managed to get my local ILP kit exposed to the internet over localtunnel. It was an easy change; I only had to modify the URIs in my env.list, and then forward port 80 over localtunnel. A couple notable things:

* The connection over localtunnel is quite slow, but that might be acceptable for people testing this.
* nginx setup was still required, but the domain didn't need to be entered into the nginx config.

**Comment by emschwartz** [comment]
I think slow is okay but we should be able to make it work without nginx

**Comment by sharafian** [comment]
Looks like it works when you forward `3010` instead of `80`/`443`

**Comment by emschwartz** [comment]
Does that cause any issues with the ledger being reachable?

**Comment by sharafian** [comment]
nope. It essentially does the same thing as nginx, by proxying `localhost:3010` to `subdomain.localhost.me:443`. You can even leave everything using https.

**Comment by vhpoet** [comment]
We have docker now and even if you're not using a docker, the webserver file should do all of the port forwarding / cert stuff.
