### ISSUE TITLE
multi hop payments

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#108]
Let's say I want to pay from neil@ledgerA (GBP) to mike@ledgerB (USD) but my preferred connector doesn't support USD so it has to go through a second connector (EUR) that can do business to USD.
That is, from GBP to EUR to USD.

is this supported as of now in ilp-kit?

**Comment by justmoon** [comment]
Yes, this is supported! The `ilp-connector` that is part of `ilp-kit` will broadcast its known destinations to other connectors and those will rebroadcast those routes, in turn, applying their own rates on top.

There is a ton of work still to be done on the routing protocol, but if everything is set up correctly and the network isn't too large (lots of scalability improvements are still in the pipeline) it will work.

**Comment by justmoon** [comment]
If you'd like to see the routing algorithm in action, check out the demo: https://github.com/interledgerjs/five-bells-demo
