### ISSUE TITLE
trying to create an 'undefined' account

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#112]
[api] 2016-12-10T11:00:01.504Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2016-12-10T11:00:01.531Z ledger:koa info <-- GET /accounts/admin
[ledger] 2016-12-10T11:00:01.576Z ledger:koa info --> GET /accounts/admin 200 45ms 201B
[ledger] 2016-12-10T11:00:01.580Z ledger:koa info <-- PUT /accounts/admin
[ledger] 2016-12-10T11:00:01.626Z ledger:koa info --> PUT /accounts/admin 200 46ms 160B
[api] 2016-12-10T11:00:01.626Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = NULL LIMIT 1;
[api] 2016-12-10T11:00:01.697Z sequelize DEBUG Executing (default): INSERT INTO "Users" ("account","updated_at","created_at") VALUES ('https://hola.ilp.network/ledger/accounts/undefined','2016-12-10 11:00:01.685 +00:00','2016-12-10 11:00:01.685 +00:00') RETURNING *;
[ledger] 2016-12-10T11:00:01.706Z ledger:koa info <-- PUT /accounts/undefined
[ledger] 2016-12-10T11:00:01.722Z ledger:error-handler warn Invalid body: Body did not match schema Account
[ledger] 2016-12-10T11:00:01.729Z ledger:koa info --> PUT /accounts/undefined 400 23ms 1.5KB

**Comment by Winthan** [comment]
Due to this error, it got stuck with API. 
-----
```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/nyeinminn/.nvm/versions/node/v6.9.1/bin/node" "/home/nyeinminn/.nvm/versions/node/v6.9.1/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ilp-kit@1.0.0 start: `DEBUG_COLORS=1 concurrently -p "[{name}]" -n "ledger,connector,api,wallet" -c "red,magenta,blue,cyan" "npm run start-prod-ledger" "npm run start-prod-connector" "npm run start-prod-api" "npm run start-prod"`
npm ERR! Exit status 137
```
----
```
[wallet] events.js:160
[wallet]       throw er; // Unhandled 'error' event
[wallet]       ^
[wallet] 
[wallet] Error: listen EADDRINUSE :::3101
[wallet]     at Object.exports._errnoException (util.js:1026:11)
[wallet]     at exports._exceptionWithHostPort (util.js:1049:20)
[wallet]     at Server._listen2 (net.js:1257:14)
[wallet]     at listen (net.js:1293:10)
[wallet]     at Server.listen (net.js:1389:5)
[wallet]     at Object.<anonymous> (/home/nyeinminn/ilp/src/server.js:161:10)
[wallet]     at Module._compile (module.js:570:32)

```
---

```
[wallet] proxy error { Error: connect ECONNREFUSED ::1:3101
[wallet]     at Object.exports._errnoException (util.js:1026:11)
[wallet]     at exports._exceptionWithHostPort (util.js:1049:20)
```
Mostly it is happending due to stucking at above issues.
 
When you end  with killall -9 node, it doesn't kill all, You can still opening port with "netstat -l"
for some reasons, 3101 still listens. You have to run killall two times to close the 3101.  

However, if you run again, you will get issue with 3101 port in-use issues and refusing port at 3101, again for some reasons.

**Comment by elmurci** [comment]
That's another issue.
You still have an instance running...

**Comment by vhpoet** [comment]
This is due to a bug on the connector account creation code, will push a fix soon.
