### ISSUE TITLE
Database sanitization for production 

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#115]
In the table of Users, I see that admin URL is having the wallet1 domain, instead of the domain we set on env.list for production. 

  1 | admin    | http://wallet1.com/ledger/accounts/admin

**Comment by vhpoet** [comment]
[This commit](https://github.com/interledgerjs/ilp-kit/commit/35b7377ed0514d9e96e73945d3471ce68ef313ef) removes the unused `account` field from the `Users` table.
