### ISSUE TITLE
Yahoo Exchange API Than Fixer.io API

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#123]
Can we use Yahoo Exchange API to cover all pairs of currencies for peer connectors?

`https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.xchange where pair in ("USDAUD", "USDAED", "USDARS", "USDAOA", "USDBGN", "USDBRL", "USDBTC", "USDBRL", "USDCAD", "USDCHF", "USDCNY", "USDCZK", "USDDKK", "USDEUR", "USDGBP", "USDHKD", "USDHRK", "USDHUF", "USDIDR", "USDILS", "USDISK", "USDLTL", "USDLVL", "USDRON", "USDJPY", "USDKRW", "USDMMK", "USDMXN", "USDMYR", "USDMZN", "USDNOK", "USDNGN", "USDNZD", "USDPHP", "USDPLN", "USDRON", "USDRUB", "USDSEK", "USDSGD", "USDTHB", "USDTRY", "USDTWD", "USDXAG", "USDXAU", "USDZAR")&env=store://datatables.org/alltableswithkeys&format=json
`

You can simply request to get one pair for exchange rates. 

`https://query.yahooapis.com/v1/public/yql?q=select * from yahoo.finance.xchange where pair in   ("USDGBP")&env=store://datatables.org/alltableswithkeys&format=json
`

**Comment by vhpoet** [comment]
@sentientwaffle @sharafian

**Comment by emschwartz** [comment]
This should work: https://github.com/interledgerjs/ilp-connector-backend-yahoo

**Comment by Winthan** [comment]
@emschwartz Thank you, Evan!
