### ISSUE TITLE
Version tagging in env.list

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-kit#128]
If your config version doesn't match your ILP Kit version, you can run into a lot of hard-to-interpret errors. It's hard to keep up with all the changes sometimes.

We should add a field to the ILP Kit config file that says the version of ILP Kit (and/or of ILP Kit CLI) that the config file was created for. When `npm run configure` is run (or in some cases, `npm run peer`), it should update the version field appropriately.

At startup, if the ILP Kit's version isn't compatible with the version noted in the config, it should either emit a (very visible) warning, or refuse to start altogether.

**Comment by vhpoet** [comment]
Does ilp-kit-cli already have the versioning?

**Comment by sharafian** [comment]
ILP Kit doesn't include a version in the env.list yet. I could make it include the `ilp-kit-cli` version though, and then the ILP kit could check to make sure that the version in the env.list that it's parsing matches the version of `ilp-kit-cli` that it has listed in it's package.json.

**Comment by vhpoet** [comment]
@sharafian sounds good

**Comment by vhpoet** [comment]
already implemented.
