### ISSUE TITLE
AssetsNotTradedError : This connector does not support the given asset pair

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#132]
After trying to get a quote for ZAR pair without adding peer key of za.zar.hopebailie. 

`[connector] 2016-12-15T03:04:31.737Z connector:route-builder info creating quote sourceAddress=us.usd.interledger.winthan sourceAmount=11 destinationAddress=za.zar.hopebailie.win destinationAmount=undefined destinationPrecisionAndScale=undefined slippage=undefined`

it shows 
`destinationAmount=undefined destinationPrecisionAndScale=undefined slippage=undefined`
```

[ledger] 2016-12-15T03:04:31.770Z ledger:koa info <-- POST /messages
[ledger] 2016-12-15T03:04:31.784Z ledger:koa info --> POST /messages 201 14ms 351B
[connector] 2016-12-15T03:04:31.789Z connector:message-router warn got error message: {"id":"AssetsNotTradedError","message":"This connector does not support the given asset pair"}
[api] Error: Got empty quote response from the connector
[api]     at client.connect.then.then.then (/home/winthan/ilp-kit/node_modules/ilp/src/lib/sender.js:55:17)
[api] 2016-12-15T03:04:31.793Z error-handler WARN Not Found: No quote for a specified destination/amount has been found
[api] 2016-12-15T03:04:31.797Z http INFO   --> POST /payments/quote 404 1,189ms -
```

Do I need to get their public keys from another node in order to get quote and connector work? 

My dep version
```
├─┬ ilp@7.1.0
├─┬ ilp-connector@12.4.3
 ├─┬ ilp-kit-cli@9.0.1
├─┬ ilp-plugin-bells@9.2.1
├─┬ ilp-plugin-virtual@9.0.1 
├─┬ five-bells-ledger@19.3.0
├─┬ five-bells-condition@3.3.1
├─┬ five-bells-shared@14.1.2 
├─┬ UNMET PEER DEPENDENCY react@15.4.1 
npm ERR! peer dep missing: react@0.14.x, required by redux-async-connect@1.0.0-rc4
```

**Comment by sharafian** [comment]
Depending on your peers, you might not have any route to `za.zar.hopebailie`. You don't necessarily need to be peered with `za.zar.hopebailie`, but you do need to be peered with someone who is peered with `za.zar.hopebailie` (or someone peered with them, or so on).

Once you're peered with someone who has `za.zar.hopebailie` in their routing table, they'll broadcast that route to you, and you'll be able to quote to that ledger.
