### ISSUE TITLE
Long address hangs off the side of the send money box

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#133]
![image](https://cloud.githubusercontent.com/assets/3262610/21215738/0c689d20-c2b4-11e6-96de-60d61b0b3aed.png)

**Comment by Winthan** [comment]
Applying CSS will be good enough to have ellipsis if the address is long than the UI box.  
  ```
  max-width: 95%;
    overflow: hidden;
    text-overflow: ellipsis;
```

![Image of Yaktocat](https://s30.postimg.org/6anif5h4h/Screen_Shot_2016_12_16_at_10_23_51_AM.png)
