### ISSUE TITLE
Random Peer Keys in ENV.List

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#139]
Adding Peer Public Key generates a random prefix in CONNECTOR_LEDGERS at env.list while adding the key, which causes a problem getting a quote. 

```
"peer.ZA7pw.usd.": ..... ,"prefix":"peer.ZA7pw.usd.", "connector":"peer.ZA7pw.usd........"
```
After editing those peer name and prefix with a real prefix. The ledger seems ONLY giving a quote when you have right prefix and connector.

**Comment by sharafian** [comment]
The prefix isn't random; it's the HMAC of the shared secret between your key and your peer's key. If you any your peer have entered each other's public keys correctly, then you will have the same prefix for your trust-line.

The way that route broadcasting works uses the prefix of each ledger in the route. So if I think the trust-line is called `peer.a` and my peer thinks it's called `peer.b`, we won't be able to broadcast routes to one another that go through the trust-line.

If you find that the peering process isn't generating identical prefixes on both sides, though, that could be a problem.

**Comment by Winthan** [comment]
@sharafian Now it works without modifying to ENV.list.
