### ISSUE TITLE
Peer information via UI at Admin Setting

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#142]
Adding peer information via UI doesn't work yet for transfer/quote.  

There is no connector info pair and route-broadcaster info broadcasting peers at all. 

Only adding peers with command  "npm run peer" for ENV.list works only for now.  But ENV.list should have peers info correctly than having random peer info.

**Comment by vhpoet** [comment]
@Winthan It's not fully implemented yet. I should've worked on a separate branch.
