### ISSUE TITLE
Config value API_PUBLIC_HTTPS is treated as string, should be boolean

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#145]
In [bin/normalizeEnv.js](https://github.com/interledgerjs/ilp-kit/blob/master/bin/normalizeEnv.js#L71), the config value `API_PUBLIC_HTTPS` is read in to determine if the ilp-kit should use https. By default, `npm run configure` sets this value to `1` and https is turned on. However, when setting the value to `0` the check in [line 71](https://github.com/interledgerjs/ilp-kit/blob/master/bin/normalizeEnv.js#L71) is still truthy and, hence, https is not disabled as expected.

**Comment by vhpoet** [comment]
@sharafian can you change those to `true/false` instead of `0/1`? The parsing is done using the `five-bells-shared` so it's a standard.

**Comment by sharafian** [comment]
Fixed in https://github.com/interledgerjs/ilp-kit-cli/commit/7f7e9487b60f7ab61143aa425a6c1c234c524353 .

**Comment by dappelt** [comment]
I was running in the same problem again. This time the `API_PUBLIC_HTTPS` was set to the string literal `false`, which in turn was evaluated to boolean true (non-empty strings are truthy).

I propose [f341145](https://github.com/interledgerjs/ilp-kit/commit/f341145cb49e10987fbc329712a5f0d0e25f25e6) to fix the issue.
