### ISSUE TITLE
Better HTTP support

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#148]
To make the setup of `ilp-kit` easier and faster, it should be possible to use plain HTTP. HTTPS is hard-coded [in some places](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/config.js#L73).

Related to [Add simpler (or local) deploy option for testing and hackathons](https://github.com/interledgerjs/ilp-kit/issues/107#issuecomment-268419173).

**Comment by vhpoet** [comment]
@dappelt webfinger library doesn't work with the http at the moment. See https://github.com/e14n/webfinger/issues/27.

**Comment by vhpoet** [comment]
oh wait, webfinger spec says `HTTPS` is required.

https://tools.ietf.org/html/rfc7033

```
 A WebFinger request is an HTTPS request to a WebFinger resource.  A
   WebFinger resource is a well-known URI [3] using the HTTPS scheme
   constructed along with the required query target and optional link
   relation types.  WebFinger resources MUST NOT be served with any
   other URI scheme (such as HTTP).
```

**Comment by dappelt** [comment]
Update: webfinger seems to support HTTP if the request is to `localhost`
