### ISSUE TITLE
Remove postgres dependency

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#150]
Right now the biggest barrier to getting the kit [up and running quickly](https://github.com/interledgerjs/ilp-kit/issues/107) is the dependency on Postgres. Installing the extra dependencies makes it more annoying to go through the steps and adds to the time.

Can we make the `ilp-kit` work with `sqlite`?

**Comment by sharafian** [comment]
It looks like one of the main things that the ILP Kit api uses that isn't supported by sqlite is enum types. When I try to start my ILP Kit using a sqlite database, it complains:

```
SQLITE_ERROR: near "TYPE": syntax error
...
sql: 'CREATE TYPE "public"."enum_Payments_state" AS ENUM(\'pending\', \'success\', \'fail\')'
```

**Comment by vhpoet** [comment]
`enum` is not the biggest concern, there's also a `date_trunc` which is pretty important for grouping payments together. Sure we can implement it without that too, it would just take more resources, but the question I have is how do we look at the `ilp-kit` in general. The flexibility and ease of the installation means compromising on a lot of good things that postgres and other _not very flexible_ tools and libraries provide.

**Comment by emschwartz** [comment]
@vhpoet are there other good things? The ones you mention seem pretty minor to me. I think the first step to getting lots of people using `ilp-kit` is making it as easy as possible to install and play around with it. Since Postgres can be annoying to install I think it would be better to require that only if you want a permanent installation.

**Comment by vhpoet** [comment]
I think you won the argument, just give me some time to get rid of the postgres specific things.

**Comment by vhpoet** [comment]
just pushed https://github.com/interledgerjs/ilp-kit/commit/10c0cc9b60ef99f6ee1d79ffb7ec49a6236aa1d1. Is there anything else left to do?
