### ISSUE TITLE
routes broadcasting - multi hop

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#153]
If my understanding is correct connectors should broadcast supported destinations to other connectors and those will rebroadcast those routes.

`Connector A` is connected to `Connector B` and they both will share their routes.
As `Connector B` is also connected to `Connector C`, they both will share whatever routes they are connected to and those will come back back to `Connector A`.

So, at some point:

1. Someone initiates a payment from `Connector A` to an account in a ledger linked with `Connector C`
2. `Connector A` is aware of `Connector C` although does not hold a direct relationship with it. As it knows that `Connector B` does have it, will route the payment through `Connector B`.

Is my understanding correct?

If so, is there any issue with Connectors broadcasting routes? 
My connectors does not seem to broadcast routes to other connectors... and that is causing multi hop payments to fail as routes are not in the RoutingTables object and returns an error on quoting.

**Comment by emschwartz** [comment]
Your description of the routing process is correct.

Have you peered with other ILP kits? What does the `CONNECTOR_PEERS` environment variable in your `env.list` say?

**Comment by sharafian** [comment]
Actually, could you make sure `CONNECTOR_AUTOLOAD_PEERS` is set to `true`, and the trustlines have the same prefixes in their`CONNECTOR_LEDGERS` fields? (`CONNECTOR_PEERS` is no longer configured manually)

**Comment by elmurci** [comment]
In practice.

`hola.ilp.network` -> `milton.ilp.network` -> `cornelius.sharafian.com`

Payments between `hola.ilp.network` -> `milton.ilp.network`  and `milton.ilp.network` -> `cornelius.sharafian.com` work fine.

Payments between `hola.ilp.network`  -> `cornelius.sharafian.com` fail due to connector not finding an available quote (RoutingTables does not reflect `cornelius.sharafian.com` on `hola.ilp.network`)

**hola.ilp.network**
```
CONNECTOR_AUTOLOAD_PEERS=true
CONNECTOR_ENABLE=true
CONNECTOR_LEDGERS={"gb.gbp.milton.":{"plugin":"ilp-plugin-bells","currency":"GBP","options":{"identifier":"hola@milton.ilp.network","password":"******"}},"es.eur.hola.":{"currency":"EUR","plugin":"ilp-plugin-bells","options":{"account":"https://hola.ilp.network/ledger/accounts/inaki","password":"******"}}}
CONNECTOR_LOG_LEVEL=debug
CONNECTOR_MAX_HOLD_TIME=100
CONNECTOR_PEERS=gb.gbp.milton.hola
CONNECTOR_PORT=4000
```

_In the log:_
`[connector] 2016-12-23T15:58:23.789Z connector:route-broadcaster info broadcasting 2 routes to gb.gbp.milton.javi`

**milton.ilp.network**
```
CONNECTOR_AUTOLOAD_PEERS=true
CONNECTOR_ENABLE=true
CONNECTOR_LEDGERS={"us.usd.cornelius.":{"plugin":"ilp-plugin-bells","currency":"USD","options":{"identifier":"javi@cornelius.sharafian.com","password":"******"}},"es.eur.hola.":{"plugin":"ilp-plugin-bells","currency":"EUR","options":{"identifier":"javi@hola.ilp.network","password":"******"}},"gb.gbp.milton.":{"currency":"GBP","plugin":"ilp-plugin-bells","options":{"account":"https://milton.ilp.network/ledger/accounts/javi","password":"******"}}}
CONNECTOR_LOG_LEVEL=debug
CONNECTOR_MAX_HOLD_TIME=100
CONNECTOR_PEERS=us.usd.cornelius.sharafian, es.eur.hola.ilp.network.javi
CONNECTOR_PORT=4000
```
_In the log:_
`
[connector] 2016-12-23T15:56:26.722Z connector:route-broadcaster info broadcasting 2 routes to es.eur.hola.inaki`
`[connector] 2016-12-23T15:56:26.722Z connector:route-broadcaster info broadcasting 2 routes to us.usd.cornelius.sharafian
`

**cornelius.sharafian.com**
_Maybe you can help with this one_ @sharafian :-)

**Comment by sharafian** [comment]
Can you make sure that `LEDGER_RECOMMENDED_CONNECTORS` includes `javi,hola` on both of your ledgers?

**Comment by sharafian** [comment]
Alternatively, you can switch to using [trustline-based peering](https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md#connecting-your-ledger)

**Comment by elmurci** [comment]
Hey @sharafian, yes that did the trick. Didn't make sense to add `javi,hola` on both though. Did the following:

**hola.ilp.network**
`LEDGER_RECOMMENDED_CONNECTORS=inaki,javi`

**milton.ilp.network**
`LEDGER_RECOMMENDED_CONNECTORS=javi,hola`
