### ISSUE TITLE
HTTP requests are send to 443

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#155]
When setting `API_PUBLIC_HTTPS=false` in `env.list`, some HTTP requests are still send to port 443, but via `HTTP`, e.g.:
```
[api] 2016-12-23T17:50:19.053Z app INFO public at http://wallet1.com:443/api
```

In consequence, Apache complains that HTTP is the wrong protocol:
```
[api] utils:39 { Error: Bad Request
[api]     at Request.callback (/Users/da/git/interledgerjs/ilp-kit/node_modules/superagent/lib/node/index.js:698:17)
[api]     at IncomingMessage.<anonymous> (/Users/da/git/interledgerjs/ilp-kit/node_modules/superagent/lib/node/index.js:922:12)
[api]     at emitNone (events.js:91:20)
[api]     at IncomingMessage.emit (events.js:185:7)
[api]     at endReadableNT (_stream_readable.js:974:12)
[api]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[api]     at process._tickCallback (internal/process/next_tick.js:98:9)
....
[api]         req: [Object],
[api]         text: '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\nReason: You\'re speaking plain HTTP to an SSL-enabled server port.<br />\n Instead use the HTTPS scheme to access this URL, please.<br />\n</p>\n</body></html>\n',
....
```

**Comment by vhpoet** [comment]
I need to update the environment variables, but `HTTP` is not supposed to work with the ilp kit, use `HTTPS` instead.

**Comment by vhpoet** [comment]
Removed the env variable https://github.com/interledgerjs/ilp-kit/commit/8eb5b9a308d9d95141baffd0287bbc3ba9c97406.

**Comment by dappelt** [comment]
@vhpoet. Instead of removing `API_PUBLIC_HTTPS` and `LEDGER_PUBLIC_HTTPS` completely, we probably should move them to the dev instructions.

The ilp kit supports HTTP on localhost (refer to [issues/148](https://github.com/interledgerjs/ilp-kit/issues/148) ), which makes development and testing easier. I think `API_PUBLIC_HTTPS` should be allowed to be true if `API_HOSTNAME` is `localhost`. This should be explained in the dev readme. 

Do you agree?
