### ISSUE TITLE
Network analytics

### ISSUE THREAD

**Issue by diminator** [interledgerjs/ilp-kit#174]
Currently we have about a network of 10-20 nodes that *might* be up and running.

It's not really clear what's the current state of the network.
Maybe it's interesting to have a network visualization or analytics tool, mainly for debugging?

- shows the connectors/ledgers that can be discovered
- provide basic info about the connectors/ledgers (SW, version, health, ...)
- packet throughput (delivery, loss, ...)

**Comment by vhpoet** [comment]
@diminator working on it! :)

**Comment by sharafian** [comment]
If every ILP Kit reported their own ilp addresses and their peers' ilp addresses, we could show a graph of the network.

**Comment by emschwartz** [comment]
It would also be cool to show `ilp-kit` users where they can send money to

**Comment by vhpoet** [comment]
@diminator http://connector.land/

**Comment by diminator** [comment]
sweet!

now I'll need to figure out why my status is red ;-)

**Comment by vhpoet** [comment]
@diminator update your kit!

**Comment by michielbdejong** [comment]
@diminator which one is yours? I'll peer with you! :)

Btw, current master might be broken, at least people were having some trouble yesterday. Maybe better try revision 772f4c6f849384353da856d9c1a9e0b4f3fddc57. It can also sometimes help to remove everything under your node_modules folder and install all dependencies from scratch.

**Comment by diminator** [comment]
Hi @michielbdejong I've updated but remains a 502 in connector.land
What's the best way for peering up?
