### ISSUE TITLE
Auto-update?

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#175]
If we want to make sure people are running recent versions of the `ilp-kit`, should we have an optional auto-update feature?

**Comment by justmoon** [comment]
Maybe just a nag screen / email notification when there is a new version? Auto update can easily be turned into a "take over the whole network" security vulnerability.

(Not that manually updating isn't dangerous, too, but at least people update at different times, so an attacker will have difficulty getting to as many people.)

**Comment by vhpoet** [comment]
@justmoon oh and a notification would be 1000x easier to implement :)

**Comment by justmoon** [comment]
Notification it is then!

**Comment by michielbdejong** [comment]
@vhpoet do you want me to have a look at this? I think it would really help to grow the community network. One approach would be:

* fetch https://raw.githubusercontent.com/interledgerjs/ilp-kit/master/package.json and see if the version number there is higher than the version running locally
* if it is, display a notifications saying "Please log into your server and run npm update. See <updating> for more help."
* this should probably only happen if the logged-in user is the admin.
* create an 'updating' docs page with some instructions for different situations (like running Heroku)

**Comment by justmoon** [comment]
Sounds good to me!

**Comment by vhpoet** [comment]
@michielbdejong sounds great. You could use the `<Alert>` for that too (see the top blue bar).
<img width="1232" alt="screen shot 2017-03-13 at 7 59 49 am" src="https://cloud.githubusercontent.com/assets/686185/23860075/0a75f77a-07c3-11e7-9711-677437fd3d88.png">

**Comment by vhpoet** [comment]
@michielbdejong are you working on this or should I take over?

**Comment by vhpoet** [comment]
It looks like this now, am I missing anything?

<img width="578" alt="screen shot 2017-05-26 at 12 25 03 pm" src="https://cloud.githubusercontent.com/assets/686185/26509718/d67dcd9a-420e-11e7-8d4f-8389f930a31c.png">
