### ISSUE TITLE
Invite code should be a link

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#185]
When you generate an invite code it would be ideal to have a full link the invitee can click on to get straight to the register page with the invite code filled in. Right now it's unclear from the admin API what to do with the codes and you really have to look to find what to do with it as the invitee.

**Comment by vhpoet** [comment]
@emschwartz clicking on the invite code copies the full link, would you rather see the whole link in UI?

**Comment by emschwartz** [comment]
It looks to me like it just links to `kit.example/invites`, has that changed in a newer version?

**Comment by vhpoet** [comment]
Tooltip fixed in https://github.com/interledgerjs/ilp-kit/commit/bdfa5421ed13c39bcdc3d5bcf4228fb5a2caffaf.
