### ISSUE TITLE
Sender can get charged more than what he agreed to send

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#199]
When sending a payment via the ILP kit, there are [two quote requests](https://github.com/interledgerjs/ilp-kit/blob/b6ca3c428d0e52f4fc97aacf60e5aba2487cf707/api/src/lib/spsp.js#L139): The first is sent when the user fills in the payment amount in the UI and the second one when the user hits the send button. This opens up a potential attack vector: The user agrees to the conditions of the first quote before hitting the send button, but then the ILP kit automatically sends a payment with the conditions of the second quote. The second quote might be different from the first, e.g. the `sourceAmount` might be higher.

Is it necessary to send the second quote request or can we send the payment with the first quote? Even if the exchange rate fluctuates, this is accounted for by the slippage.

**Comment by vhpoet** [comment]
yep, it's a todo https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/spsp.js#L142

**Comment by vhpoet** [comment]
@dappelt actually that's [already done](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/spsp.js#L150-L152). There's a 1% slippage.

**Comment by dappelt** [comment]
This checks only that the `destinationAmount` has not changed more than 1%. `sourceAmount` needs to be checked too.

In fact, instead of checking that the amounts did not change it would be better to do only one quote request. Currently there are two quote requests: First, when the user fills in `sourceAmount` or `destinationAmount` in the UI there is a call to [`quoteDestinationAmount()`](https://github.com/interledgerjs/ilp-kit/blob/b6ca3c428d0e52f4fc97aacf60e5aba2487cf707/api/src/lib/spsp.js#L102)or [`quoteSourceAmount()`](https://github.com/interledgerjs/ilp-kit/blob/b6ca3c428d0e52f4fc97aacf60e5aba2487cf707/api/src/lib/spsp.js#L106), respectively. Then, there is another quote request once the user hits the pay button in [`setup()`](https://github.com/interledgerjs/ilp-kit/blob/b6ca3c428d0e52f4fc97aacf60e5aba2487cf707/api/src/lib/spsp.js#L117).

It would be better if [`setup()`](https://github.com/interledgerjs/ilp-kit/blob/b6ca3c428d0e52f4fc97aacf60e5aba2487cf707/api/src/lib/spsp.js#L117) would be already called when the user enters the `sourceAmount` or `destinationAmount`. This way we could skip checking that the amounts did not change altogether.

**Comment by vhpoet** [comment]
@dappelt you're right, it only checks `destinationAmount`.

Calling `setup()` on every quote request is very expensive.

**Comment by emschwartz** [comment]
Luckily the whole setup step is being taken out of SPSP https://github.com/interledgerjs/ilp/pull/64

**Comment by sharafian** [comment]
This is no longer an issue; The payment is quoted, and then the quote displayed in the UI is sent.
