### ISSUE TITLE
Thumbnails don't render on settlement method

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-kit#200]
<img width="276" alt="screen shot 2017-02-08 at 11 04 43 am" src="https://cloud.githubusercontent.com/assets/3362563/22732460/8dc31228-edee-11e6-96e2-f2569f4491c2.png">

**Comment by vhpoet** [comment]
@sharafian have you uploaded a settlement method logo?

**Comment by vhpoet** [comment]
@sharafian is this still an issue?
