### ISSUE TITLE
Remove need for manual psql, nginx, and letsencrypt setup

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#201]
Say I own a domain name, and create a server from scratch, to install ilp-kit on a subdomain (for instance, ilp-kit.michielbdejong.com). It should be enough to:

* spin up your server, install requirements (could be either node or docker)
* point the subdomain to your server
* clone this repo onto the server
* from the repo root, run: `./setup.sh ilp-kit.michielbdejong.com`

This setup.sh should take care of:

* initialize psql
* either `npm start` or `docker run` (doesn't really matter which one it is under the hood)
* display a link in the terminal/cli output which logs you straight into your ilp-kit, as admin
* display a list of next steps:
  * point to wiki page with recommended peers
  * send your first payment (should explain you need to ask a peer to peer back with you first)
  * receive your first payment (should explain 'this is your spsp address, this is your ledger prefix, etc)
  * point to docs about github/mailgun integration

**Comment by emschwartz** [comment]
If we have that kind of setup.sh script we could even have one of those really insecure but popular "paste this curl...sudo sh... commands into your terminal" lines

**Comment by sharafian** [comment]
I think `curl ... | sudo sh` is too scary

**Comment by michielbdejong** [comment]
Fixed in https://github.com/interledgerjs/ilp-kit/pull/226
