### ISSUE TITLE
Cannot log in after adding certain peers

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#204]
Certain peers lead to the following error when you add them:

````
[api] 
[api] TypeError: links.map is not a function
[api]     at WebFinger.__processJRD (/home/michiel/ilp-kit/node_modules/webfinger.js/src/webfinger.js:212:11)
[api]     at /home/michiel/ilp-kit/node_modules/webfinger.js/src/webfinger.js:310:14
[api]     at __processState (/home/michiel/ilp-kit/node_modules/webfinger.js/src/webfinger.js:111:18)
[api]     at xhr.onreadystatechange (/home/michiel/ilp-kit/node_modules/webfinger.js/src/webfinger.js:148:11)
[api]     at dispatchEvent (/home/michiel/ilp-kit/node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
[api]     at setState (/home/michiel/ilp-kit/node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
[api]     at IncomingMessage.<anonymous> (/home/michiel/ilp-kit/node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
[api]     at emitNone (events.js:91:20)
[api]     at IncomingMessage.emit (events.js:185:7)
[api]     at endReadableNT (_stream_readable.js:974:12)
[api]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[api]     at process._tickCallback (internal/process/next_tick.js:98:9)
````

After that, the (admin) user will be logged out, and unable to log in again, until you manually remove the peer in question from the database.

An example of a peer with which I discovered this behavior is kes-ilp.abdishakur.com.

**Comment by sharafian** [comment]
```
{
    "links": {
        "href": "https://kes-ilp.abdishakur.com/ledger",
        "rel": "https://interledger.org/rel/ledgerUri"
    },
    "properties": {
        "https://interledger.org/rel/publicKey": "kaGWHS6ryuTUVL/mq3jnwAoHk29yntaN9HVQ3Mr+mL0="
    },
    "subject": "https://kes-ilp.abdishakur.com"
}
```

Yeah, the links are a map here, rather than an array. Maybe this is also a bug in ILP kit that's returning that response.

**Comment by michielbdejong** [comment]
IMHO this is a problem on three layers:
* an unexpected response from another server should not cause webfinger.js to throw an error
* a bug in webfinger.js should not be able to crash the API server
* the API server should try to recover if it crashes,

**Comment by michielbdejong** [comment]
For the record, if anyone breaks their ilp-kit while trying to reproduce this bug, this is how to unbreak it (where `michiel` is the user you created during https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md):

````
sudo su - michiel
michiel@ilp:~$ psql ilpkit
psql (9.5.5)
Type "help" for help.

ilpkit=> DELETE FROM "Peers" WHERE hostname='kes-ilp.abdishakur.com';
DELETE 1
ilpkit=> \q 
michiel@ilp:~$

**Comment by michielbdejong** [comment]
I guess the desired behavior would be the peer gets added with a red dot, just like if you add unreachable123.com as a peer

**Comment by michielbdejong** [comment]
We had a chat about this. It may make sense to run the api server through something like pm2. In any case, I'll add a mocha / nock unit test for this, and also submit a fix upstream.

**Comment by michielbdejong** [comment]
Upstream fix submitted: https://github.com/silverbucket/webfinger.js/pull/22
