### ISSUE TITLE
Failing to add peers

### ISSUE THREAD

**Issue by whotooktwarden** [interledgerjs/ilp-kit#213]
I have set up an instance of ilp-kit on digitalocean and set the hostname of the instance to the IP and was successfully able to connect with my browser.  I logged into the admin account and I tried to create a trust-line with milton.ilp.network for 10 GBP then I received this error message in the terminal:  
```

[api] 2017-02-13T00:05:34.164Z http INFO   --> GET /peers 200 87ms -
[api] 2017-02-13T00:05:42.036Z http INFO   <-- POST /peers
[api] 2017-02-13T00:05:42.041Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-13T00:05:42.067Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-13T00:05:42.078Z ledger:koa info --> GET /accounts/admin 200 11ms 197B
[api] 2017-02-13T00:05:42.503Z error-handler ERROR { TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]     at Utils.hostLookup (/home/twarden/ilp-kit/api/src/lib/utils.js:161:37)
[api]     at next (native)
[api]     at onFulfilled (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7) headers: { 'Access-Control-Allow-Origin': '*' } }
[api] 2017-02-13T00:05:42.507Z error-handler ERROR TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]     at Utils.hostLookup (/home/twarden/ilp-kit/api/src/lib/utils.js:161:37)
[api]     at next (native)
[api]     at onFulfilled (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-02-13T00:05:42.508Z http INFO   xxx POST /peers 500 472ms -
[api]
[api]   InternalServerError: TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]       at Object.throw (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
[api]       at Object.handleError (/home/twarden/ilp-kit/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
[api]       at throw (native)
[api]       at onRejected (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:77:24)
[api]       at process._tickCallback (internal/process/next_tick.js:103:7)
[api]

```

I tried a few different hosts, some didn't respond, and so far I have received this error on every host that did resolve.

**Comment by vhpoet** [comment]
@whotooktwarden we haven't tested ILP Kit with IP addresses, can you attach your kit to a domain?

**Comment by whotooktwarden** [comment]
@vhpoet I binded https://www.royalcrypto.com to the IP yesterday evening.  Peers (and payments) functions still reproduce the same errors when the hostname was reset.

**Comment by vhpoet** [comment]
@whotooktwarden your setup issues seem to be related, discussing at https://github.com/interledgerjs/ilp-kit/issues/214.

**Comment by whotooktwarden** [comment]
After success with funds being allocated by using postgresql-9.6 in #214, I reattempted to create a trustline to milton.ilp.network for 10 GBP and I received this new error message within the terminal:

```
[api] 2017-02-13T23:47:04.826Z http INFO   <-- GET /peers
[api] 2017-02-13T23:47:04.876Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-13T23:47:04.947Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-13T23:47:04.978Z ledger:koa info --> GET /accounts/admin 200 32ms 203B
[api] 2017-02-13T23:47:04.991Z sequelize DEBUG Executing (default): SELECT "Peer"."id", "Peer"."hostname", "Peer"."limit", "Peer"."currency", "Peer"."destination", "Peer"."created_at", "Peer"."updated_at" FROM "Peers" AS "Peer" ORDER BY "Peer"."created_at" DESC;
[api] 2017-02-13T23:47:05.000Z http INFO   --> GET /peers 200 174ms -
[api] 2017-02-13T23:47:40.296Z http INFO   <-- POST /peers
[api] 2017-02-13T23:47:40.317Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-13T23:47:40.354Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-13T23:47:40.374Z ledger:koa info --> GET /accounts/admin 200 20ms 203B
[api] 2017-02-13T23:47:40.992Z error-handler ERROR { TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]     at Utils.hostLookup (/home/twarden/ilp-kit/api/src/lib/utils.js:161:37)
[api]     at next (native)
[api]     at onFulfilled (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7) headers: { 'Access-Control-Allow-Origin': '*' } }
[api] 2017-02-13T23:47:40.999Z error-handler ERROR TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]     at Utils.hostLookup (/home/twarden/ilp-kit/api/src/lib/utils.js:161:37)
[api]     at next (native)
[api]     at onFulfilled (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-02-13T23:47:41.001Z http INFO   xxx POST /peers 500 704ms -
[api]
[api]   InternalServerError: TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined
[api]       at Object.throw (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
[api]       at Object.handleError (/home/twarden/ilp-kit/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
[api]       at throw (native)
[api]       at onRejected (/home/twarden/ilp-kit/node_modules/koa.io/node_modules/co/index.js:77:24)
[api]       at process._tickCallback (internal/process/next_tick.js:103:7)
[api]

```

And when I performed a second test by attempting to establish a trustline with nexus.justmoon.com for 100 USD I received the Unsupported currency error again: 
```

[api] 2017-02-13T23:50:04.893Z http INFO   <-- POST /peers
[api] 2017-02-13T23:50:04.927Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-13T23:50:04.963Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-13T23:50:05.003Z ledger:koa info --> GET /accounts/admin 200 40ms 203B
[api] 2017-02-13T23:50:05.308Z connector:ledgers info adding ledger peer.LU5yS.usd.
[api] 2017-02-13T23:50:05.373Z error-handler WARN Invalid body: Unsupported currency
[api] 2017-02-13T23:50:05.378Z http INFO   --> POST /peers 400 485ms -
```

**Comment by vhpoet** [comment]
@whotooktwarden 

`Cannot read property 'https://interledger.org/rel/publicKey' of undefined`

this is thrown when the peer host doesn't respond with a valid webfinger result. `https://{host}/api/webfinger?resource={host}`. Please check if this link returns a valid json for all of the peers.

**Comment by whotooktwarden** [comment]
In my web browser or with curl I get this result:

```
[twarden@u19195387 ilp-kit]$ curl -X GET https://milton.ilp.network/api/webfinger?resource=milton.ilp.network
{"id":"NotFoundError","message":"Unknown account"}[twarden@u19195387 ilp-kit]$
[twarden@u19195387 ilp-kit]$ curl -X GET https://royalcrypto.com/api/webfinger?resource=royalcrypto.com
{"id":"NotFoundError","message":"Unknown account"}[twarden@u19195387 ilp-kit]$

```

**Comment by vhpoet** [comment]
@whotooktwarden sorry it should've been `https://{host}/api/webfinger?resource=https://{host}` 

```
https://royalcrypto.com/api/webfinger?resource=https://royalcrypto.com
``` 
This works
```
https://milton.ilp.network/api/webfinger?resource=https://milton.ilp.network
```
This one seems to be an outdated `ilp-kit`

**Comment by whotooktwarden** [comment]
@vhpoet So what would the Unsupported Currency error from updated date servers mean?  Is this because I have set up my instance for BTC an not USD so this error is produced?

**Comment by vhpoet** [comment]
@whotooktwarden could you try with USD? `ilp-connector` uses fixer.io which doesn't provide rates for BTC.

**Comment by whotooktwarden** [comment]
@vhpoet Success!

`[api] 2017-02-14T19:26:26.287Z http INFO   <-- GET /peers
[api] 2017-02-14T19:26:26.303Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-14T19:26:26.329Z ledger:koa info <-- GET /accounts/admin
[api] 2017-02-14T19:26:26.352Z sequelize DEBUG Executing (default): SELECT "Peer"."id", "Peer"."hostname", "Peer"."limit", "Peer"."currency", "Peer"."destination", "Peer"."created_at", "Peer"."updated_at" FROM "Peers" AS "Peer" ORDER BY "Peer"."created_at" DESC;
[api] 2017-02-14T19:26:26.358Z http INFO   --> GET /peers 200 71ms -
[ledger] 2017-02-14T19:26:26.360Z ledger:koa info --> GET /accounts/admin 200 29ms 203B
[api] 2017-02-14T19:26:45.730Z http INFO   <-- POST /peers
[api] 2017-02-14T19:26:45.747Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-14T19:26:45.775Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-14T19:26:45.810Z ledger:koa info --> GET /accounts/admin 200 35ms 203B
[api] 2017-02-14T19:26:46.035Z connector:ledgers info adding ledger peer.LU5yS.usd.
[api] 2017-02-14T19:26:46.084Z connector:route-broadcaster info adding peer peer.LU5yS.usd.1W78wTNgWniBxOGyzLSVFJ0HvyPbCTVy57ohGzyhwC8 via ledger peer.LU5yS.usd.
[api] 2017-02-14T19:26:46.307Z sequelize DEBUG Executing (default): INSERT INTO "Peers" ("id","hostname","limit","currency","destination","updated_at","created_at") VALUES ('ce1e5cad-1415-4565-a96b-ead1ae45aa6f','nexus.justmoon.com',100,'USD',678879,'2017-02-14 19:26:46.291 +00:00','2017-02-14 19:26:46.291 +00:00') RETURNING *;
[api] 2017-02-14T19:26:46.316Z http INFO   --> POST /peers 200 586ms -
`

http://imgur.com/a/XjEpn

Is there by chance a list of currencies that are supported by ilp-connector available?

**Comment by vhpoet** [comment]
@whotooktwarden here's the list http://api.fixer.io/latest.

**Comment by emschwartz** [comment]
If you want to use other currencies, you should install a different connector backend alongside the `ilp-kit`, such as the [`ilp-connector-backend-yahoo`](https://github.com/interledgerjs/ilp-connector-backend-yahoo), which does support BTC.

If you set the environment variable `CONNECTOR_BACKEND` to `ilp-connector-backend-yahoo`, the connector will `require` that module and use it instead.

**Comment by whotooktwarden** [comment]
Thanks @emschwartz, I will look into this later 👍
