### ISSUE TITLE
If one of your peers is down, your entire peers list will look empty

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#215]
### reproduce
* check out latest master (3b85f0869)
* npm install
* restart ilp-kit and log in as admin
* ask one of your peers to Ctrl-C their ilp-kit
* refresh the Peers page

### expected
the peer that is temporarily unreachable is displayed as 'offline' in the peers list

### actual
it says 'no peers'

### workaround
tell all your peers to keep their ilp-kits running 24/7, or remove the peer that's down from the list. To do this while your peers page is broken, you can directly edit the Peers table in psql, as follows:
* sudo su - [the user you used to install ilp-kit]
* psql ilpkit
* SELECT * FROM "Peers";
* DELETE FROM "Peers" WHERE host = 'unreachable123.com';
* \q
* refresh the Peers list page in your browser
* your normal Peers list will appear again

**Comment by michielbdejong** [comment]
Wait, this may be because I didn't `npm install` after `git pull`, confirming now...

**Comment by michielbdejong** [comment]
With latest master, it's not possible to add a peer that's down at the moment of adding. The problem still exists if one of your existing peers is temporarily down (just tested this with @dappelt).

**Comment by dappelt** [comment]
Confirming, I am running in the same issue. This log message might be related to the error cause:
```
[api] 2017-02-13T10:40:42.236Z connector:route-broadcaster info adding peer peer.2E2AI.eur.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA via ledger peer.2E2AI.eur.
[api] { message: 'error during request',
[api]   url: 'https://ilp-kit.michielbdejong.com/.well-known/webfinger?resource=https://ilp-kit.michielbdejong.com',
[api]   status: 502,
[api]   toString: [Function] }
[api] 2017-02-13T10:40:42.313Z error-handler ERROR TypeError: Cannot read property 'ledgerName' of undefined
[api]     at Conncetor.getPeer (/home/dappelt/ilp-kit/api/src/lib/connector.js:213:48)
[api]     at throw (native)
[api]     at onRejected (/home/dappelt/ilp-kit/node_modules/co/index.js:81:24)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-02-13T10:40:42.315Z error-handler ERROR TypeError: Cannot read property 'ledgerName' of undefined
[api]     at Conncetor.getPeer (/home/dappelt/ilp-kit/api/src/lib/connector.js:213:48)
[api]     at throw (native)
[api]     at onRejected (/home/dappelt/ilp-kit/node_modules/co/index.js:81:24)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-02-13T10:40:42.317Z http INFO   ^[[31mxxx ^[[;1mGET^[[0;90m /peers ^[[31m500^[[90m 268ms -^[[0m
[api]
[api]   InternalServerError: TypeError: Cannot read property 'ledgerName' of undefined
[api]       at Object.throw (/home/dappelt/ilp-kit/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
[api]       at Object.handleError (/home/dappelt/ilp-kit/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
[api]       at throw (native)
[api]       at onRejected (/home/dappelt/ilp-kit/node_modules/koa.io/node_modules/co/index.js:77:24)
```

**Comment by michielbdejong** [comment]
Yes, let's create a unit test for this! :)
