### ISSUE TITLE
min_allowed_balance ignored by UI

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#219]
### reproduce
* register as a new user, or use an existing one - I used user `lunch` in this example.
* Set the account's minimal allowed balance through the ledger api (see docs for [api call](https://interledgerjs.github.io/five-bells-ledger/apidoc/#api-Account_Methods-PutAccount) and [fields allowed](https://interledgerjs.github.io/five-bells-ledger/apidoc/#account_object)):
````
curl -X PUT -H "Authorization: Basic ****************==" -H "Content-Type: application/json" -d '{"name": "lunch", "minimum_allowed_balance": "-100"}' https://ilp-kit.michielbdejong.com/ledger/accounts/lunch
````
* Visit https://ilp-kit.michielbdejong.com/ledger/accounts/lunch to see that it worked
* Now log in as that account and try to pay someone

### expected
It should allow this account to go below zero.

### actual
See screenshot
![screen shot 2017-02-13 at 14 00 14](https://cloud.githubusercontent.com/assets/408412/22884367/e0c7b3a2-f1f4-11e6-8eb9-fc8cb6d90caf.png)

### workaround
edit either line 65 of `src/utils/validation.js` or line 28 of `src/containers/SendForm/SendValidation.js`

**Comment by vhpoet** [comment]
@justmoon do we even want people (except admin) to play with the `min_allowed_balance` at all?

**Comment by justmoon** [comment]
`min_allowed_balance` would be used for post-funding (as opposed to pre-funding).

Post-funding could help lower the risk of large-scale failures: When a big ILP Kit owes its users and defaults, it's front page news. When the users owe the ILP Kit and one of them defaults - it's just one user and not this big disaster.

Post-funding would require quite a few features/changes and I don't think we're quite ready to tackle that. (But this issue should still be fixed.)
