### ISSUE TITLE
500 error when adding milton.ilp.network as a peer

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#225]
InternalServerError: TypeError: Cannot read property 'https://interledger.org/rel/publicKey' of undefined

**Comment by michielbdejong** [comment]
I guess it's not a big deal, but it would be nice if the API would never return a 500 error

**Comment by vhpoet** [comment]
@michielbdejong yep, will add a different error message. milton.ilp.network has an outdated ilp-kit instance, the webfinger response is wrong
