### ISSUE TITLE
502 at peer leads to 500 when listing peers?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#229]
Still investigating this together with @ivanseidel and @joaopedrovbs, but that's what it looks like

**Comment by michielbdejong** [comment]
We tried it out, and saw the same behavior, in fact it's worse: the xhr call times out when nginx on my server times out with a 504.

**Comment by vhpoet** [comment]
could you elaborate on this?

**Comment by emschwartz** [comment]
If one of your peers is down, the peers page says "You have no peers"

**Comment by vhpoet** [comment]
do you guys have the latest? I've worked on this yesterday, should've been fixed.
