### ISSUE TITLE
Peering is broken. Error is InvalidBodyError: Unsupported currency

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#232]
When adding a plugin in [api/src/lib/connector.js](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/connector.js#L120), there is an error:
```
[api] 2017-02-09T14:27:43.018Z connector ERROR Couldn't add the peer to the connector { InvalidBodyError: Unsupported currency
[api]     at Conncetor.connectPeer (/home/dappelt/ilp-kit/api/src/lib/connector.js:141:15)
[api]     at throw (native)
[api]     at onRejected (/home/dappelt/ilp-kit/node_modules/co/index.js:81:24)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7) validationErrors: undefined }
```

As far as I can tell, the reason is that `peer.currency` is `undefined` ([line 131](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/connector.js#L131)).

**Comment by dappelt** [comment]
Tried with the latest commit on `master`. The error happens for example when you try to add a new peer, e.g. https://ilp-kit.michielbdejong.com/

**Comment by vhpoet** [comment]
@dappelt does it happen when adding a peer in the UI?

**Comment by vhpoet** [comment]
@dappelt is this still an issue?

**Comment by dappelt** [comment]
Yes, it still exists. If you add a peer with an "unspported currency", it will fail as expected. However, every following attempt to add a peer (even with a supported currcency )will fail too.

![image](https://cloud.githubusercontent.com/assets/23212287/23301161/f06522c6-fa88-11e6-8534-f0fb64fe8a42.png)

![image](https://cloud.githubusercontent.com/assets/23212287/23301225/43ad949a-fa89-11e6-9e08-ccb93c870153.png)

It's not an UI issue. Refer to my first post for details on where the code fails.

**Comment by vhpoet** [comment]
@sharafian @justmoon this is a nasty issue, can we get it prioritized?

**Comment by justmoon** [comment]
Proposed a solution: https://github.com/interledgerjs/ilp-connector/issues/321
