### ISSUE TITLE
Cannot send money from Ivan to me

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#234]
Debugging this with Ivan. My ledger is in euros, I trust Ivan in BRL, and Ivan's ledger is in USD. It can't find quotes when you try to send money from Ivan to me. Will investigate further and update the title of this ticket once we find out what the problem is

**Comment by vhpoet** [comment]
@michielbdejong any news on this?

**Comment by michielbdejong** [comment]
Yes, since opening this ticket, I found out that it's hardly as scarce as I thought it was - currently connectors are often failing to quote routes. But I'll close this issue now, and investigate this issue more thoroughly after ilp-kit 2.0 comes out
