### ISSUE TITLE
Error logging in using Github button

### ISSUE THREAD

**Issue by BobWay** [interledgerjs/ilp-kit#235]
If I go to https://red.ilpdemo.org
then press the Github button
the browser hangs for a minute or so
then reports Internal Server Error

I did successfully login to Github in a previous try.
same behavior on both safari and chrome.

**Comment by sappenin** [comment]
I'm having this problem too on a fresh ILPKit install...

**Comment by vhpoet** [comment]
@BobWay @sappenin please reopen if this is still an issue on red and blue.
