### ISSUE TITLE
Initialize connector account at 0 instead of at 1000

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#236]
If we give the connector a min-allowed-balance, then it can be initialized at zero, which is functionally equivalent, but looks cleaner.

Options for the min-allowed-balance:
* 0 (some money needs to be sent out first before money can come in)
* -1000 (same value as now; not very useful if the currency is something low-value like IDR)
* the sum of all trustlines (max peer balances). downside: you have to adjust it every time one of the trustlines is added/removed/changed
* -infinity (same as admin)

**Comment by dappelt** [comment]
> the sum of all trustlines (max peer balances). downside: you have to adjust it every time one of the trustlines is added/removed/changed

I discussed this with @sharafian and we tend towards this option

**Comment by sharafian** [comment]
I think having an issuing account makes the accounting easier (you can see one negative balance that shows the total of how much you owe to your users), but allowing the connector to go negative has more conceptual symmetry with trust-lines, which can make the whole system easier to understand.

**Comment by vhpoet** [comment]
How about going with the 3rd option but instead of going negative, have the admin send `trustlineLimitAmount` to the connector each time a peer is added? I like the idea of having a single issuer, and every other account `min_allowed_balalnce = 0`.. much easier for accounting.

**Comment by michielbdejong** [comment]
> you can see one negative balance that shows the total of how much you owe to your users

Right now we don't have that, since the initial `admin` balance of -$1000 is a randomly chosen number and is unrelated to what the admin owes its users (unless you consider the connector account an imaginary first user of your ledger).  

Variation on @vhpoet's proposal: do a transaction from admin to connector each time a trustline is *used* (not each time it's added), equal to the currency-equivalent of the outgoing amount. That way, the admin's negative balance is how much money has been issued by the ledger, and the connector's positive balance is how much has been earned in connector fees and slippage.

**Comment by peterjkrey** [comment]
I think this is resolved as far as I can tell? Should this be closed? @vhpoet
