### ISSUE TITLE
Loading bar on the top keeps reloading

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#246]
The bar at the top keeps reloading. I assume [this commit](https://github.com/interledgerjs/ilp-kit/commit/fac301b86413314399442d3096bedede427f233e) is related to the problem, but it did not solve it for me.

In case it is a browser specific thing, I am using Firefox 51.0.1.

**Comment by vhpoet** [comment]
reported https://github.com/mironov/react-redux-loading-bar/issues/30

**Comment by oluckyman** [comment]
having that bug too
![fxmbur6bdu](https://cloud.githubusercontent.com/assets/642673/23252649/e2ee0ac2-f9b1-11e6-8f96-189fe16b5821.gif)

**Comment by vhpoet** [comment]
fixed.
