### ISSUE TITLE
UI issue: payment recipient is not displayed

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#250]
The text entered in the payment recipient text box is not correctly displayed. I am using Firefox, it seems to work with Chromium.

It worked yesterday, so I assume it must be a commit that has been merged since yesterday.

**Comment by vhpoet** [comment]
@dappelt screenshot?

**Comment by dappelt** [comment]
The first screenshot shows what you see after entering `admin@cornelius.sharafian.com` in the text box and the focus is on the textbox. The second with developer console open.

![image](https://cloud.githubusercontent.com/assets/23212287/23253517/252c8b90-f9b5-11e6-9a80-3ea663fc3b7f.png)

![screen shot 2017-02-23 at 10 54 46](https://cloud.githubusercontent.com/assets/23212287/23253947/87ecfb9c-f9b6-11e6-9ac5-cb96ba6a47ee.png)
