### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#252]
Rather than using the Basic Base64 Authentication in all subsequent calls. Can we generate API session key as auth_token, and use as authentication in all subsequent calls?

And we can put session to an end, either manually calling "log out" event or by timing out in the kit.

**Comment by dappelt** [comment]
Thanks for the suggestion. The API supports cookie-based authentication that works in a similar way to what you describe. You can find more information on the [login](https://interledgerjs.github.io/ilp-kit/apidoc/#api-Auth-Login) and [logout](https://interledgerjs.github.io/ilp-kit/apidoc/#api-Auth-Logout) functionality in the documentation.
