### ISSUE TITLE
Full Path Disclosure 

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#254]
`curl -X PUT -H "Authorization: Basic XXXXXXXXXX=" -H "Content-Type: application/json" -d '{  "destination": "account@interledger", "sourceAmount": "5",  "destinationAmount": "5", "message": "Some money for you!" }' https://interledger/api/payments/9efa70ec-08b9-11e6-b512-3e1d05defe78 
`
In error respond of "Payment - Make payment", there is the revelation of the full operating path. 

> {"id":"InvalidBodyError","message":"Body did not match schema Payment","validationErrors":[{"message":"Invalid type: string (expected number)","params":{"type":"string","expected":"number"},"code":0,"dataPath":"/sourceAmount","schemaPath":"/properties/sourceAmount/type","subErrors":null,"stack":"Error\n    at new ValidationError (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1461:12)\n    at ValidatorContext.createError (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:359:14)\n    at ValidatorContext.validateType (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:751:14)\n    at ValidatorContext.validateBasic (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:721:19)\n    at ValidatorContext.validateAll (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:599:19)\n    at ValidatorContext.validateObjectProperties (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1010:21)\n    at ValidatorContext.validateObject (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:961:11)\n    at ValidatorContext.validateAll (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:603:11)\n    at Object.validateMultiple (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1597:12)\n    at Function.validateExternal (/home/ledger/ilp-kit/node_modules/five-bells-shared/lib/validator.js:76:31)\n    at Object.<anonymous> (/home/ledger/ilp-kit/api/src/models/payment.js:45:39)\n    at next (native)\n    at onFulfilled (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)\n    at /home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:50:5\n    at Object.co (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:49:10)\n    at Object.toPromise (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:114:63)\n    at next (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:95:29)\n    at onFulfilled (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:65:7)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"},{"message":"Invalid type: string (expected number)","params":{"type":"string","expected":"number"},"code":0,"dataPath":"/destinationAmount","schemaPath":"/properties/destinationAmount/type","subErrors":null,"stack":"Error\n    at new ValidationError (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1461:12)\n    at ValidatorContext.createError (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:359:14)\n    at ValidatorContext.validateType (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:751:14)\n    at ValidatorContext.validateBasic (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:721:19)\n    at ValidatorContext.validateAll (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:599:19)\n    at ValidatorContext.validateObjectProperties (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1010:21)\n    at ValidatorContext.validateObject (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:961:11)\n    at ValidatorContext.validateAll (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:603:11)\n    at Object.validateMultiple (/home/ledger/ilp-kit/node_modules/tv4/tv4.js:1597:12)\n    at Function.validateExternal (/home/ledger/ilp-kit/node_modules/five-bells-shared/lib/validator.js:76:31)\n    at Object.<anonymous> (/home/ledger/ilp-kit/api/src/models/payment.js:45:39)\n    at next (native)\n    at onFulfilled (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:61:19)\n    at /home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:50:5\n    at Object.co (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:49:10)\n    at Object.toPromise (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:114:63)\n    at next (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:95:29)\n    at onFulfilled (/home/ledger/ilp-kit/node_modules/koa.io/node_modules/co/index.js:65:7)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"}]}

By the way, at  Make payment method,  how do I get the generate ID?  I don't find in API Docs.

**Comment by dappelt** [comment]
Thanks for the heads-up.

> By the way, at Make payment method, how do I get the generate ID? I don't find in API Docs.

The sender generates the payment id. In your curl example, the id is `9efa70ec-08b9-11e6-b512-3e1d05defe78`.

**Comment by Winthan** [comment]
@dappelt I know that part of ID. 

my question is that where did sender generate that ID? How does the sender generate the ID to make payment?

**Comment by Winthan** [comment]
For some reasons, I am still seeing the full path.

**Comment by Winthan** [comment]
it is fixed.
