### ISSUE TITLE
Peers page is empty if a single peer is down

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#258]
I have a couple of peers. One of them is down and this seems to cause none of the other peers to be displayed on the peers page. Here is the error message when loading the peers page: https://gist.github.com/dappelt/d95d0122305c63e16aeede51208fc2f4

**Comment by dappelt** [comment]
The problem does not seems to be limited to displaying peers, but my ilp kit apparently thinks it's not connected to any other ledger.

![image](https://cloud.githubusercontent.com/assets/23212287/23404872/91583ff2-fdb7-11e6-9b8f-682c3d0cf3ef.png)

**Comment by Winthan** [comment]
if you try to add after removing those peers, the latest ILP kit will not show peer adding the option at all. I am having the same issue with it.

**Comment by vhpoet** [comment]
couldn't reproduce it, but [this](https://github.com/interledgerjs/ilp-kit/commit/346ce90dbb5654f66cfff76c07cf319fe59dcc92) will hopefully fix it. Please let me know how it goes.

**Comment by dappelt** [comment]
Seems to be fixed.
