### ISSUE TITLE
Peer Issue

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#259]
It is getting "Unsupported currency" at "Peer Adding" on admin Kit. You cannot add on any Peers due to such error. 

```
[api]  connector:ledgers info adding ledger peer.TZzCS.usd.
[api] error-handler WARN Invalid body: Unsupported currency
[api] http INFO   --> POST /peers 400 349ms

```

When API have no peers connection on Kit, route-broadcaster warns.  

```
[api] connector:route-broadcaster warn broadcasting routes failed
[api] connector:route-broadcaster warn broadcasting routes failed
[api] connector:route-broadcaster warn broadcasting routes failed
[api] connector:route-broadcaster warn broadcasting routes failed

```
Can we make [Yahoo Connector](https://github.com/interledgerjs/ilp-connector-backend-yahoo) default for Peer Connector? Because it supports more currencies and digital assets than current default fixerio connector. 

Test on fresh Install Kit  - ILP_KIT_CLI_VERSION=11.1.0

**Comment by dappelt** [comment]
Thanks for reporting. At the moment, adding a peer will fail if you tried before to add a peer with an unsupported currency. We are [working](https://github.com/interledgerjs/ilp-kit/issues/232) on it. For now, try to restart your ilp kit if you are running into this issue.

**Comment by Winthan** [comment]
it is fixed.
