### ISSUE TITLE
InvalidBodyError during make payment

### ISSUE THREAD

**Issue by prashkale** [interledgerjs/ilp-kit#262]
Deployed the ILP-kit on an ubuntu linux environment and able to create users. When making payment from one user to another, getting the InvalidBodyError as response. What could be the problem?

Request Body:
{
"destination": "nagmani",
    "sourceAmount": 5,
    "destinationAmount": 5,
    "message": "Some money for you!"
}

Response:
{
  "id": "InvalidBodyError",
  "message": ""
}

**Comment by vhpoet** [comment]
@prashkale is that a put request? what's the url?

**Comment by vhpoet** [comment]
Hey @prashkale, does this still happen? If yes, could you please include a bit more details and logs?

**Comment by prashkale** [comment]
Yes. 
URL: http://services-uscentral.skytap.com:10504/payments/metcoders
Request:
{
	"destination": "nagmani@services-uscentral.skytap.com",
	"destinationAmount": 5,
	"message": "Test"
}
Headers:
Content-Type - application/json
Authorization - Basic bWV0Y29kZXJzOm1ldGxpZmUx

Response:
{
  "id": "InvalidBodyError",
  "message": ""
}

Logs:
[api] 2017-03-10T03:48:48.606Z http INFO   <-- PUT /payments/metcoders
[api] 2017-03-10T03:48:48.620Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE ("User"."username" = 'metcoders' OR "User"."email" = 'metcoders') LIMIT 1;
[ledger] 2017-03-10T03:48:48.629Z ledger:koa info <-- GET /accounts/metcoders
[ledger] 2017-03-10T03:48:48.649Z ledger:koa info --> GET /accounts/metcoders 200 19ms 211B
[api] 2017-03-10T03:48:48.654Z error-handler WARN Invalid body:
[api] 2017-03-10T03:48:48.655Z http INFO   --> PUT /payments/metcoders 400 50ms -

Note: I have used the id/password for metcoders as the basic authorization. Let know if that is correct or not

**Comment by vhpoet** [comment]
@prashkale the `paymentId` should be a UUID in the url 

`http://services-uscentral.skytap.com:10504/payments/metcoders` should be something like `http://services-uscentral.skytap.com:10504/payments/9efa70ec-08b9-11e6-b512-3e1d05defe78`.

Please reopen if it still doesn't work after fixing this.
