### ISSUE TITLE
Switch to using ilp-packet component

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-kit#269]
- [x] New ILP packet format
- [x] New conditions
- [x] Support new SPSP/PSK

**Comment by dappelt** [comment]
When implementing the new SPSP/PSK, make sure to address [issues/199](https://github.com/interledgerjs/ilp-kit/issues/199).

**Comment by michielbdejong** [comment]
ilp-kit now uses all latest version of all new components.

**Comment by michielbdejong** [comment]
Ah wait, we don't use https://github.com/interledgerjs/ilp-packet
