### ISSUE TITLE
write a migration script for the peers v1 -> v2

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-kit#287]

**Comment by michielbdejong** [comment]
We just came up with the following compromise:
* Version 2.0 will remember who you peered with,
* will remember what maximum (`limit`) both they and you set,

And:
* the trustline will go down as soon as one of the parties upgrades,
* it will automatically start working again as soon as the other party upgrades as well,

But:
* Your balance will be reset to zero,
* The other person's balance will be reset to zero,
* (therefore) disputed balance will be reset to zero.

See also https://en.wikipedia.org/wiki/Debt_relief - David Graeber would love this :)

**Comment by michielbdejong** [comment]
done.
