### ISSUE TITLE
Fix unit tests for modified currencySymbol and currencyScale

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#293]
This [commit](https://github.com/interledgerjs/ilp-kit/commit/c30f77d579b3bcb4cffa7080794d12945be260f0) introduces changes that let some [unit tests](https://github.com/interledgerjs/ilp-kit/pull/292/commits/062af15e0832ff547c09857d944ec7d29a7e6be7) fail. The unit tests should be updated to test the newly introduced changes.

**Comment by michielbdejong** [comment]
sounds like a fixture issue, will have a look, thanks!

**Comment by dappelt** [comment]
@michielbdejong  This is fixed, no?

**Comment by michielbdejong** [comment]
Yes, thanks for the reminder.
