### ISSUE TITLE
Installation fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by nuevax** [interledgerjs/ilp-kit#298]
I tried to install on a Ubuntu srv installation but get

yarn install v0.23.2
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
**_warning "redux-async-connect@1.0.0-rc4" has incorrect peer dependency "react@0.14.x"._**

when running I get error message from pm2 logs:

**_2|web      | Error: Cannot find module 'redux/actions/auth'_**

**Comment by michielbdejong** [comment]
Hi @nuevax, thanks for reporting! This was an upstream problem which has given us big headaches as well, but it seems to have dissappeared now (maybe enough people complained upstream?).

Please try to reinstall now (remove your `node_modules` folder first to be sure you get all the latest versions of dependencies) and let us know if you still see this problem.

**Comment by nuevax** [comment]
the last problem has disappeared, however when running 'npm run configure' I now get

npm ERR! Linux 2.6.32-042stab113.17
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "configure"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ilp-kit@1.2.1 configure: `./node_modules/ilp-kit-cli/bin/configure.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ilp-kit@1.2.1 configure script './node_modules/ilp-kit-cli/bin/configure.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ilp-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/ilp-kit-cli/bin/configure.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ilp-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ilp-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ilp/.npm/_logs/2017-04-28T18_47_30_443Z-debug.log

**Comment by dappelt** [comment]
@sharafian any idea?

**Comment by sharafian** [comment]
That was https://github.com/interledgerjs/ilp-kit-cli/issues/33 , which is now fixed

**Comment by nuevax** [comment]
thanks for the response. I re-installed from scratch, however
configure.js is still the old one. When manually edited it works and
submits.
