### ISSUE TITLE
Why Express and Kao?

### ISSUE THREAD

**Issue by opiepj** [interledgerjs/ilp-kit#299]
I've noticed you have both express and kao on the repo, why not one over the other?

**Comment by vhpoet** [comment]
@opiepj you're right, only koa should be used. Express was in the frontend boilerplate that we used (for serving the static stuff).

**Comment by vhpoet** [comment]
With the v4 there's no server side rendering anymore, so the client doesn't use a webserver. Now we use koa for the api and express for the webserver just out of convenience.
