### ISSUE TITLE
List of connectable peers is not auto populated

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#301]
Would be ideally a drop down list automatically populated with connectable peers

**Comment by michielbdejong** [comment]
You can discover connectable peers on https://connector.land. How about just adding a hyperlink?

**Comment by vhpoet** [comment]
@peterjkrey which peers are shown in that dropdown?

**Comment by peterjkrey** [comment]
Right now there is just a list of recently entered addresses.  I was simply suggesting it populate with a list of all available other ILP Kits within its network scope.

**Comment by michielbdejong** [comment]
@peterjkrey how will you collect and distribute this information? A list published on connector.land which ilp-kit can pull in live during setup, I guess?

**Comment by peterjkrey** [comment]
I think for now, to keep it simple, just a default hard coded list for now [https://grifiti.web-payments.net, ilp-kit.michielbdejong.com, nexus.justmoon.com, etc] of the servers we know will be up hosted by Ripple staff will do.  The goal is to make this as streamlined as possible for new users, and not have them get lost on any step to get setup because of an empty field.

**Comment by michielbdejong** [comment]
ok, but then you might as well retrieve that list from http://connector.land/data/hosts.js

**Comment by peterjkrey** [comment]
I would say that this is not a priority at the moment and will close it for now.  More important to flush out other things that prevent correct behavior of the application.
