### ISSUE TITLE
ILP Kit configuration CLI

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#302]
Multiple people when setting up the ILP Kit have incorrectly assumed this to be hardcoded or overlooked it leading to errors when running ILP Kit:
Posgres DB URI: postgres://sharafian:PASSWORD@localhost/ilpkit

The CLI should ask for the Posgres DB username and password, then build the URI.

https://github.com/interledgerjs/ilp-kit/blob/new_setup/docs/SETUP.md#configure-environment

**Comment by michielbdejong** [comment]
Fixed in #306
