### ISSUE TITLE
Payment fails from admin to user on ilpkit 2.0.0

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#303]
Payment is made from admin to user on same connector ilp kit;

[ledger] 2017-04-17T23:12:50.220Z ledger:error-handler error error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)
[ledger] 2017-04-17T23:12:50.220Z ledger:koa info xxx PUT /transfers/ad242528-7e89-4e6d-9022-f921aa39f799/fulfillment 500 14ms -
[ledger] 2017-04-17T23:12:51.329Z ledger:koa info <-- PUT /transfers/ad242528-7e89-4e6d-9022-f921aa39f799/fulfillment
[ledger] 2017-04-17T23:12:51.343Z ledger:error-handler error { error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)
[ledger]   name: 'error',
[ledger]   length: 85,
[ledger]   severity: 'ERROR',
[ledger]   code: '42601',
[ledger]   detail: undefined,
[ledger]   hint: undefined,
[ledger]   position: '135',
[ledger]   internalPosition: undefined,
[ledger]   internalQuery: undefined,
[ledger]   where: undefined,
[ledger]   schema: undefined,
[ledger]   table: undefined,
[ledger]   column: undefined,
[ledger]   dataType: undefined,
[ledger]   constraint: undefined,
[ledger]   file: 'scan.l',
[ledger]   line: '1053',
[ledger]   routine: 'scanner_yyerror' }
[ledger] 2017-04-17T23:12:51.343Z ledger:error-handler error error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)
[ledger] 2017-04-17T23:12:51.344Z ledger:koa info xxx PUT /transfers/ad242528-7e89-4e6d-9022-f921aa39f799/fulfillment 500 15ms -
[ledger] 2017-04-17T23:12:52.443Z ledger:koa info <-- PUT /transfers/ad242528-7e89-4e6d-9022-f921aa39f799/fulfillment
[ledger] 2017-04-17T23:12:52.457Z ledger:error-handler error { error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)
[ledger]   name: 'error',
[ledger]   length: 85,
[ledger]   severity: 'ERROR',
[ledger]   code: '42601',
[ledger]   detail: undefined,
[ledger]   hint: undefined,
[ledger]   position: '135',
[ledger]   internalPosition: undefined,
[ledger]   internalQuery: undefined,
[ledger]   where: undefined,
[ledger]   schema: undefined,
[ledger]   table: undefined,
[ledger]   column: undefined,
[ledger]   dataType: undefined,
[ledger]   constraint: undefined,
[ledger]   file: 'scan.l',
[ledger]   line: '1053',
[ledger]   routine: 'scanner_yyerror' }
[ledger] 2017-04-17T23:12:52.457Z ledger:error-handler error error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)

**Comment by dappelt** [comment]
What version of postgres do you use?

**Comment by peterjkrey** [comment]
pkrey@grifiti ~/ilp-kit> psql --version
**psql (PostgreSQL) 9.3.16**

**Comment by peterjkrey** [comment]
[ledger] 2017-04-19T03:01:06.380Z ledger:error-handler error error: syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/pkrey/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:189:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:551:20)
[ledger] 2017-04-19T03:01:06.380Z ledger:koa info xxx PUT /transfers/758d021f-9e3a-4ba4-885c-27b936d63554/fulfillment 500 43ms -
[api] Error: transfer 758d021f-9e3a-4ba4-885c-27b936d63554 failed.
[api]     at FiveBellsLedger.cancel (/home/pkrey/ilp-kit/node_modules/ilp/src/lib/spsp.js:213:14)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:437:31)
[api]     at FiveBellsLedger._handleNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:695:26)
[api]     at _handleNotification.next (<anonymous>)
[api]     at FiveBellsLedger._handleNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:695:26)                                                [0/1836]
[api]     at _handleNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at PluginFactory._routeNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:115:43)
[api]     at _routeNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at PluginFactory.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at PluginFactory.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at FiveBellsLedger.adminPlugin.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:52:42)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:434:31)
[api]     at FiveBellsLedger._handleIncomingRpcMessage (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:683:18)
[api]     at _handleIncomingRpcMessage.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at WebSocket.ws.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:250:16)
[api]     at emitTwo (events.js:106:13)
[api]     at WebSocket.emit (events.js:192:7)
[api]     at Receiver.ontext (/home/pkrey/ilp-kit/node_modules/ws/lib/WebSocket.js:841:10)
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:536:18
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:368:7
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/PerMessageDeflate.js:249:5
[api]     at afterWrite (_stream_writable.js:383:3)
[api]     at onwrite (_stream_writable.js:374:7)
[api]     at afterTransform (_stream_transform.js:79:3)
[api]     at TransformState.afterTransform (_stream_transform.js:54:12)
[api]     at Zlib.callback (zlib.js:625:5)
[api] 2017-04-19T03:01:06.805Z error-handler WARN Server error:
[api] 2017-04-19T03:01:06.806Z http INFO   --> PUT /payments/758d021f-9e3a-4ba4-885c-27b936d63554 500 10s -
[ledger] 2017-04-19T03:01:07.490Z ledger:koa info <-- PUT /transfers/758d021f-9e3a-4ba4-885c-27b936d63554/fulfillment
[ledger] 2017-04-19T03:01:07.503Z ledger:error-handler warn Expired Transfer: Cannot modify transfer after expires_at date
[ledger] 2017-04-19T03:01:07.504Z ledger:koa info --> PUT /transfers/758d021f-9e3a-4ba4-885c-27b936d63554/fulfillment 422 14ms 86B
[ledger] 2017-04-19T03:01:07.615Z ledger:koa info <-- PUT /transfers/758d021f-9e3a-4ba4-885c-27b936d63554/rejection
[ledger] 2017-04-19T03:01:07.629Z ledger:error-handler warn Expired Transfer: Cannot modify transfer after expires_at date
[ledger] 2017-04-19T03:01:07.630Z ledger:koa info --> PUT /transfers/758d021f-9e3a-4ba4-885c-27b936d63554/rejection 422 15ms 86B

Upgraded postgresql to 9.5 but error still happens

**Comment by dappelt** [comment]
Since the stack trace seems to not be very helpful, I just grepped trough the code to find the problematic line. [Here](https://github.com/interledgerjs/five-bells-ledger/blob/master/src/models/db/utils.js#L46) is it.

The syntax it is choking on is ` ON CONFLICT DO NOTHING`, which was introduced with postgres 9.5. If you are sure that you are using at least version 9.5, can you log the SQL statement stored in `sql`?

**Comment by peterjkrey** [comment]
I am able to confirm this was a postgres versioning issue.  On Ubuntu you must do a full wipe of Postgres 9.3, stop all postgres services, install Postgres 9.5, then start services.

**Comment by peterjkrey** [comment]
http://stackoverflow.com/questions/2748607/how-to-thoroughly-purge-and-reinstall-postgresql-on-ubuntu

```
apt-get --purge remove postgresql\*
rm -r /etc/postgresql/
rm -r /etc/postgresql-common/
rm -r /var/lib/postgresql/
userdel -r postgres
groupdel postgres
apt-get install postgresql-9.5 postgresql-contrib-9.5 postgresql-doc-9.5
```
