### ISSUE TITLE
Script to clear configuration

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#304]
When upgrading to a new ILP Kit version, need script to eliminate dangling processes, env variables etc.

**Comment by michielbdejong** [comment]
The env variables are loaded from `env.list`, or in server deploy configuration, can you give an example where you have an env variable from a previous ilp-kit version that needs to be eliminated?

Stopping currently running processes is taken care of by the `pm stop` commands in https://github.com/interledgerjs/ilp-kit/blob/master/docs/UPGRADE.md#upgrading-your-ilp-kit.

Does that address this issue sufficiently?

**Comment by peterjkrey** [comment]
I think the correct process for this is to also wipe out the existing ilpkit database on postgres as well

**Comment by michielbdejong** [comment]
There are migration scripts that take care of changes to db schemas. No need to wipe the database.

If the correct process for upgrading ilpkit would include wiping the database then people would not upgrade very often :)

**Comment by michielbdejong** [comment]
Closing this now; @peterjkrey please reopen if this still causes you problems.
