### ISSUE TITLE
Cannot refresh when on 'Peers' page

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#328]
The only way to reach the `/peers` page is to navigate to it using the menu, you can't load it directly by its URL. For instance, when I open https://ilp-kit.michielbdejong.com/peers in my browser, the page doesn't load. I have to load https://ilp-kit.michielbdejong.com/ instead, and then click 'Peers' from there.

**Comment by vhpoet** [comment]
dup of https://github.com/interledgerjs/ilp-kit/issues/273.
