### ISSUE TITLE
initial connector funding is failing in integration tests

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#335]
https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/app.js#L111
calls https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/pay.js#L21
calls https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/spsp.js#L63
calls https://github.com/interledgerjs/ilp/blob/master/src/lib/spsp.js#L175
which fails because the spsp details are missing.

The ilp-kit integration test logs the error:
```
ilp-kit[Wallet2] [api] 2017-04-28T13:31:04.809Z app CRIT { AssertionError: missing SPSP response in payment
ilp-kit[Wallet2] [api]     at Object.sendPayment (/app/integration-test/ilp-kit/node_modules/ilp/src/lib/spsp.js:178:3)
```
and continues, so the tests pass, but it's still broken (probably if you install ilp-kit from scratch now, the connector will not be funded).

**Comment by dappelt** [comment]
I will have a look

**Comment by dappelt** [comment]
I fixed ILP kit to corretly call the SPSP API and the initial funding is now send to the connector. However, the connector is notified about the payment he rejects it ... This is the message:

```
ilp-kit[Wallet1] [api] 2017-05-02T14:11:31.648Z connector:payments debug rejecting incoming transfer id=01d2237e-68ba-4b5d-8023-59f1271fb63d reason={"triggered_by":"us.usd.wallet1.connie","triggered_at":"2017-05-02T14:11:31.648Z","additional_info":{},"code":"S02","name":"Unreachable","message":"No route found from: us.usd.wallet1. to: us.usd.wallet1.connie.8QLr-0lKvYgx32i-Th3yXMQsHxjcSOJLg"}
```

**Comment by dappelt** [comment]
Update: There is already another issue for the connector not being able to receive payments: #316 

Let's close this issue and continue the problem with the connector receiving payments in the reference issue.
