### ISSUE TITLE
cannot set profile picture

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#340]
The `/null?` part of this URL looks wrong:

<img width="1160" alt="screen shot 2017-05-02 at 14 01 44" src="https://cloud.githubusercontent.com/assets/408412/25616952/f84446d4-2f3f-11e7-984e-760f7a663daf.png">

**Comment by sharafian** [comment]
Did you enter an email and a current password? The box will be greyed out until you do that
