### ISSUE TITLE
Show default picture if a user has not set it's profile picture

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#342]
If a sender/receiver did not set his profile picture, the payment history looks like this:

![image](https://cloud.githubusercontent.com/assets/23212287/25617140/1e7bc858-2f41-11e7-8c2d-79df17664d6b.png)

Instead, it should show the placeholder image:
![image](https://cloud.githubusercontent.com/assets/23212287/25617164/422e4da2-2f41-11e7-862d-fe639c985ffa.png)

**Comment by dappelt** [comment]
Also, if the sender/receiver has not set his name it will show up as _null paid you_

![image](https://cloud.githubusercontent.com/assets/23212287/25617237/94350de8-2f41-11e7-9b06-5f9c19a2d8d7.png)

**Comment by vhpoet** [comment]
@dappelt couldn't reproduce it. any clues?

**Comment by sharafian** [comment]
You can reproduce the behavior if you send an interledger payment without your name set. Intra-ledger will show the username.

**Comment by vhpoet** [comment]
@sharafian the profile picture thing is solved, I was talking about the `null` paid you.

**Comment by sharafian** [comment]
that's what I'm talking about also

**Comment by sharafian** [comment]
actually it looks like although it happens sometimes, that doesn't consistently reproduce the behavior. I think it might get triggered if webfinger is having problems when you send?
