### ISSUE TITLE
Peers appear to be offline 

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#361]
Commit 4bb574a on master branch now all peers appear offline

![peers](https://cloud.githubusercontent.com/assets/4540878/25816838/42db9370-33da-11e7-9b56-eae41864466a.jpeg)
[api] 2017-05-08T17:18:25.267Z sequelize DEBUG Executing (default): SELECT "Peer"."id", "Peer"."hostname", "Peer"."limit", "Peer"."currencyCode", "Peer"."currencyScale", "Peer"."destination", "Peer"."created_at", "Peer"."updated_at" FROM "Peers" AS "Peer" ORDER BY "Peer"."created_at" DESC;
[api] 2017-05-08T17:18:25.268Z socket INFO Subscribe admin
[api] 2017-05-08T17:18:25.274Z connector:ledgers info adding ledger peer.Kx4wC.usd.9.
[api] 2017-05-08T17:18:25.280Z connector:ledgers info adding ledger peer.FBER0.usd.9.
[api] 2017-05-08T17:18:25.286Z connector:ledgers info adding ledger peer.BinUF.usd.9.
[api] 2017-05-08T17:18:25.293Z connector:ledgers info adding ledger peer.6jcWG.usd.9.
[api] 2017-05-08T17:18:25.298Z connector:ledgers info adding ledger peer.PF8gn.usd.9.
[api] 2017-05-08T17:18:25.304Z connector:ledgers info adding ledger peer.fJbTC.usd.9.
[api] 2017-05-08T17:18:25.419Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.420Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.476Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.511Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.596Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.597Z http INFO   --> GET /peers 200 940ms -
[api] 2017-05-08T17:18:25.668Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.943Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:25.947Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:26.064Z http INFO   <-- GET /webfinger/?resource=https://grifiti.web-payments.net
[api] 2017-05-08T17:18:26.069Z http INFO   --> GET /webfinger/?resource=https://grifiti.web-payments.net 200 5ms -
[api] 2017-05-08T17:18:26.092Z connector INFO Can't get the peer limit
[api] 2017-05-08T17:18:26.093Z http INFO   --> GET /peers 200 854ms -
[api] 2017-05-08T17:18:35.402Z connector:route-broadcaster info broadcasting 1 routes to peer.fJbTC.usd.9.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk
[api] 2017-05-08T17:18:35.403Z connector:route-broadcaster info broadcasting 1 routes to peer.PF8gn.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8
[api] 2017-05-08T17:18:35.404Z connector:route-broadcaster info broadcasting 1 routes to peer.6jcWG.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ
[api] 2017-05-08T17:18:35.404Z connector:route-broadcaster info broadcasting 1 routes to peer.BinUF.usd.9.Znxdzaz2bQvgy3nJcq81JvYV-dOjMn3xBXx9qQQ0Xl4
[api] 2017-05-08T17:18:35.405Z connector:route-broadcaster info broadcasting 1 routes to peer.FBER0.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg
[api] 2017-05-08T17:18:35.405Z connector:route-broadcaster info broadcasting 1 routes to peer.Kx4wC.usd.9.mAnGASctQQjhVXE-EYUEG4ip3UXJKVx659KfoaBMUBw
[api] 2017-05-08T17:18:35.451Z connector:route-broadcaster info detectedDown! account: peer.fJbTC.usd.9.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk lostLedgerLinks: []
[api] 2017-05-08T17:18:35.452Z connector:route-broadcaster warn broadcasting routes to peer.fJbTC.usd.9.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk failed
[api] 2017-05-08T17:18:35.612Z http INFO   <-- GET /webfinger/?resource=https://grifiti.web-payments.net
[api] 2017-05-08T17:18:35.616Z http INFO   --> GET /webfinger/?resource=https://grifiti.web-payments.net 200 4ms -
[api] 2017-05-08T17:18:35.661Z connector:route-broadcaster info detectedDown! account: peer.FBER0.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg lostLedgerLinks: []
[api] 2017-05-08T17:18:35.662Z connector:route-broadcaster warn broadcasting routes to peer.FBER0.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg failed
[api] 2017-05-08T17:18:35.939Z connector:route-broadcaster info detectedDown! account: peer.PF8gn.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 lostLedgerLinks: []
[api] 2017-05-08T17:18:35.939Z connector:route-broadcaster warn broadcasting routes to peer.PF8gn.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 failed
[api] 2017-05-08T17:18:35.975Z connector:route-broadcaster info detectedDown! account: peer.6jcWG.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ lostLedgerLinks: []
[api] 2017-05-08T17:18:35.975Z connector:route-broadcaster warn broadcasting routes to peer.6jcWG.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ failed
[api] 2017-05-08T17:18:36.124Z connector:route-broadcaster info detectedDown! account: peer.Kx4wC.usd.9.mAnGASctQQjhVXE-EYUEG4ip3UXJKVx659KfoaBMUBw lostLedgerLinks: []
[api] 2017-05-08T17:18:36.124Z connector:route-broadcaster warn broadcasting routes to peer.Kx4wC.usd.9.mAnGASctQQjhVXE-EYUEG4ip3UXJKVx659KfoaBMUBw failed

![peers](https://cloud.githubusercontent.com/assets/4540878/25817835/6c4032b8-33dd-11e7-8219-b60ce18d0d9e.jpeg)

**Comment by vhpoet** [comment]
@peterjkrey v2.0 is not compatible with v1.0, if you've peered on v1.0 please remove all the peers and peer again. Feel free to reopen this if it still happens.
