### ISSUE TITLE
Changes to trust limit do not save

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#367]
![trustlimit2](https://cloud.githubusercontent.com/assets/4540878/25865092/9ade1030-34a6-11e7-883a-6edd0d0e33b7.jpeg)
![trustlimit](https://cloud.githubusercontent.com/assets/4540878/25865093/9ae0ba10-34a6-11e7-958c-5be720eb5d40.jpeg)

**Comment by peterjkrey** [comment]
Attempting to change the limit that I am willing to extend someone else does not save.

**Comment by vhpoet** [comment]
didn't 30 turn into 20?

**Comment by justmoon** [comment]
Reload resets it to what it was before.

**Comment by peterjkrey** [comment]
this has been fixed.
