### ISSUE TITLE
Custom deposit methods failing

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#368]
![deposit](https://cloud.githubusercontent.com/assets/4540878/25867607/e6b8b408-34ae-11e7-902c-de5f698313a8.jpeg)

**Comment by peterjkrey** [comment]
![deposit_fail](https://cloud.githubusercontent.com/assets/4540878/25867627/035bb394-34af-11e7-9b41-ed3fc9aa2bff.jpeg)

**Comment by vhpoet** [comment]
@peterjkrey did you set a deposit method url?

**Comment by peterjkrey** [comment]
No I set it to empty.  You should not need one for cash, which was why I left it blank.
