### ISSUE TITLE
Zero in upper left of email confirm set

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#369]
![image](https://cloud.githubusercontent.com/assets/4540878/25870446/f63635f4-34b8-11e7-99a1-ef80d81036b7.png)

**Comment by peterjkrey** [comment]
the '0' in the upper left should not be there

**Comment by vhpoet** [comment]
fixed in https://github.com/interledgerjs/ilp-kit/commit/3fdd2909c2289cbd66ee66db6b728962ac8f977d
