### ISSUE TITLE
Logs showing 'cant get peer limit'

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#370]
[api] 2017-05-09T20:31:37.074Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.149Z connector:route-broadcaster info detectedDown! account: peer.FBER0.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg lost
LedgerLinks: []
[api] 2017-05-09T20:31:37.149Z connector:route-broadcaster warn broadcasting routes to peer.FBER0.usd.9.RaDX8ZREv6KSi55fqCQb4cE-631PaWZaiNdAOnAFXHg fail
ed
[api] 2017-05-09T20:31:37.240Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.360Z connector:route-broadcaster info detectedDown! account: peer.ThnyW.usd.9.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA lost
LedgerLinks: []
[api] 2017-05-09T20:31:37.360Z connector:route-broadcaster warn broadcasting routes to peer.ThnyW.usd.9.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA fail
ed
[api] 2017-05-09T20:31:37.364Z connector:route-broadcaster info detectedDown! account: peer.6jcWG.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ lost
LedgerLinks: []
[api] 2017-05-09T20:31:37.364Z connector:route-broadcaster warn broadcasting routes to peer.6jcWG.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ fail
ed
[api] 2017-05-09T20:31:37.384Z connector:route-broadcaster info detectedDown! account: peer.PF8gn.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 lost
LedgerLinks: []
[api] 2017-05-09T20:31:37.385Z connector:route-broadcaster warn broadcasting routes to peer.PF8gn.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 fail
ed
[api] 2017-05-09T20:31:37.463Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.519Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.521Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.532Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:37.533Z http INFO   --> GET /peers 200 686ms -
[api] 2017-05-09T20:31:44.280Z http INFO   <-- GET /settlement_methods
[api] 2017-05-09T20:31:44.282Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T20:31:44.295Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T20:31:44.301Z ledger:koa info --> GET /accounts/admin 200 5ms 219B
[api] 2017-05-09T20:31:44.301Z sequelize DEBUG Executing (default): SELECT "SettlementMethod"."id", "SettlementMethod"."type", "SettlementMethod"."name"
, "SettlementMethod"."logo", "SettlementMethod"."description", "SettlementMethod"."uri", "SettlementMethod"."enabled", "SettlementMethod"."options", "Se
ttlementMethod"."created_at", "SettlementMethod"."updated_at" FROM "SettlementMethods" AS "SettlementMethod" ORDER BY "SettlementMethod"."enabled" DESC,
 "SettlementMethod"."created_at" ASC;
[api] 2017-05-09T20:31:44.303Z http INFO   --> GET /settlement_methods 200 24ms -
[api] 2017-05-09T20:31:55.082Z http INFO   <-- GET /peers
[api] 2017-05-09T20:31:55.091Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T20:31:55.114Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T20:31:55.119Z ledger:koa info --> GET /accounts/admin 200 5ms 219B
[api] peers reached
[api] 2017-05-09T20:31:55.121Z sequelize DEBUG Executing (default): SELECT "Peer"."id", "Peer"."hostname", "Peer"."limit", "Peer"."currencyCode", "Peer"
."currencyScale", "Peer"."destination", "Peer"."created_at", "Peer"."updated_at" FROM "Peers" AS "Peer" ORDER BY "Peer"."created_at" DESC;
[api] 2017-05-09T20:31:55.124Z connector:ledgers info adding ledger peer.I4RPd.usd.9.
[api] 2017-05-09T20:31:55.131Z connector:ledgers info adding ledger peer.ThnyW.usd.9.
[api] 2017-05-09T20:31:55.136Z connector:ledgers info adding ledger peer.PF8gn.usd.9.
[api] 2017-05-09T20:31:55.142Z connector:ledgers info adding ledger peer.6jcWG.usd.9.
[api] 2017-05-09T20:31:55.148Z connector:ledgers info adding ledger peer.BinUF.usd.9.
[api] 2017-05-09T20:31:55.155Z connector:ledgers info adding ledger peer.FBER0.usd.9.
[api] 2017-05-09T20:31:55.425Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.575Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.803Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.836Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.852Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.852Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:55.853Z http INFO   --> GET /peers 200 771ms -
[api] 2017-05-09T20:31:57.860Z http INFO   <-- GET /peers
[api] 2017-05-09T20:31:57.863Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T20:31:57.884Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T20:31:57.889Z ledger:koa info --> GET /accounts/admin 200 5ms 219B
[api] peers reached
[api] 2017-05-09T20:31:57.891Z sequelize DEBUG Executing (default): SELECT "Peer"."id", "Peer"."hostname", "Peer"."limit", "Peer"."currencyCode", "Peer"
."currencyScale", "Peer"."destination", "Peer"."created_at", "Peer"."updated_at" FROM "Peers" AS "Peer" ORDER BY "Peer"."created_at" DESC;
[api] 2017-05-09T20:31:57.894Z connector:ledgers info adding ledger peer.I4RPd.usd.9.
[api] 2017-05-09T20:31:57.902Z connector:ledgers info adding ledger peer.ThnyW.usd.9.
[api] 2017-05-09T20:31:57.907Z connector:ledgers info adding ledger peer.PF8gn.usd.9.
[api] 2017-05-09T20:31:57.913Z connector:ledgers info adding ledger peer.6jcWG.usd.9.
[api] 2017-05-09T20:31:57.918Z connector:ledgers info adding ledger peer.BinUF.usd.9.
[api] 2017-05-09T20:31:57.923Z connector:ledgers info adding ledger peer.FBER0.usd.9.
[api] 2017-05-09T20:31:58.117Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.251Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.505Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.524Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.537Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.560Z connector INFO Can't get the peer limit
[api] 2017-05-09T20:31:58.560Z http INFO   --> GET /peers 200 700ms -
[api] 2017-05-09T20:32:00.520Z http INFO   <-- GET /users
[api] 2017-05-09T20:32:00.522Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T20:32:00.536Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T20:32:00.543Z ledger:koa info --> GET /accounts/admin 200 7ms 219B
[ledger] 2017-05-09T20:32:00.544Z ledger:koa info <-- GET /accounts
[ledger] 2017-05-09T20:32:00.549Z ledger:koa info --> GET /accounts 200 5ms 1.3KB

**Comment by vhpoet** [comment]
@peterjkrey this is normal, it means the other side is not peered with you.
