### ISSUE TITLE
Use standardized Ripple blue color on all buttons

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#377]

**Comment by peterjkrey** [comment]
// Fonts
// -------------------------
@font-family-open-sans:                'open_sansregular', sans-serif;
@font-family-open-sans-700:        'open_sansbold', sans-serif;
@font-family-open-sans-300:        'open_sanslight', sans-serif;
@font-family-open-sans-800:        'open_sansextrabold', sans-serif;
@font-family-open-sans-800;

@small-font:                    12px;
@regular-font:                14px;
@teaser-font:                    16px;
@body-text:           17px;
@reg-plus-font:                18px;
@med-small-font:            21px;
@med-font:                        24px;
@big-font:                        36px;
@med-big-font:        48px;
@title-font:                    64px;
// Brand colors
// -------------------------

@brand-primary:        #346AA9;
@blue:                        #346AA9;
@darkblue:                #27507d;
@lightblue:                #eaf0f7;
@title-blue:      #066b98;
@title-dark-blue: #344e5a;
@baby-blue:       #27a2db;
@white:                        #fff;
@light-grey:            #F4F6F7;
@grey:                        #666666;
@line-grey:                #CCCCCC;
@font-color:            #333333;
@teaser-color:        #E5E5E5;
@dark-grey:                #999999;
@black:                        #000000;
@very-dark-grey:    #5d5e5e;
@mid-grey:        #676767;
@text-grey:       #808080;

**Comment by vhpoet** [comment]
the button colors are configurable from the `variables-custom.scss`. Every ILP Kit instance may have it's own colors.
