### ISSUE TITLE
No status on withdrawl tab + Make a payment button

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#384]
Withdrawal status not updated whether fail or success.

Should reject withdrawals for amount more than your balance, which currently succeed.

**Comment by peterjkrey** [comment]
![withdrawl](https://cloud.githubusercontent.com/assets/4540878/25879265/89865880-34e5-11e7-8321-4ccd7e1b0e3a.jpeg)

**Comment by vhpoet** [comment]
this is fixed.
