### ISSUE TITLE
Withdrawals GUI changes

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#387]
Status needs capitalization for 'Complete' or 'Pending'

Button should read 'Send Withdrawal' not 'complete'

![complete_pending](https://cloud.githubusercontent.com/assets/4540878/25879506/dc350436-34e6-11e7-9f09-b0648094e2ce.jpeg)

**Comment by vhpoet** [comment]
capitalization is fixed, but the button is the same since admin manually sends the withdrawal, and clicks complete to verify it's been sent.
