### ISSUE TITLE
Settings page has no button to return home under certain pane dimensions

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#397]
![settings_dead](https://cloud.githubusercontent.com/assets/4540878/26227887/2bd039a2-3bea-11e7-9aef-4a8e9ea78668.jpeg)

Home button is not found and picture not uploaded

**Comment by peterjkrey** [comment]
![settings_homealive](https://cloud.githubusercontent.com/assets/4540878/26227907/475974c2-3bea-11e7-9270-e0ef70a4bdad.jpeg)

When dimensions are slightly changed, home button is painted successfully.

**Comment by vhpoet** [comment]
`Activity` button on the bottom is the home page.

**Comment by peterjkrey** [comment]
It should be renamed to 'Home'

It is labeled 'Home' on the landing and therefore if not labeled the same, is confusing.

**Comment by vhpoet** [comment]
@peterjkrey home on desktop is a different page, it has both activity and send form, on a mobile activity and send are different pages.
