### ISSUE TITLE
Add risk score algorithm based on payment, deposit/withdrawal, settlement activity

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#409]
ILP Kit peers should be able to query or calculate a risk assessment score of other ILP Kits based on the behavior of them over time.  Trust goes up for other ILP Kits as they display good faith over time which can be cross validated by analyzing public payment history.

**Comment by vhpoet** [comment]
@peterjkrey this issue seems to be belonging to https://github.com/michielbdejong/connector.land

**Comment by peterjkrey** [comment]
done
https://github.com/michielbdejong/connector.land/issues/5
