### ISSUE TITLE
After unpeering, ILP kit still sends route broadcasts to the peer

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#445]
The title says it all. After unpeering, the ILP Kit's connector should no longer send route broadcasts to the ex-peer.

**Comment by michielbdejong** [comment]
This should be handled by the [removePeer](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/connector.js#L184-L196) method, maybe it's not being called or failing to do what it's supposed to do.

**Comment by dappelt** [comment]
I am having difficulties to reproduce the bug. [removePeer](https://github.com/interledgerjs/ilp-kit/blob/master/api/src/lib/connector.js#L184-L196) works as expected.

**Comment by sentientwaffle** [comment]
What's happening is this:

If `A` and `B` start out peered and `A` removes `B`:
* `A` stops broadcasting to `B` (`removePeer()` works fine).
* `B` will keep sending route broadcasts to `A`, even though they are rejected.
