### ISSUE TITLE
Client is not being updated when sending money through API

### ISSUE THREAD

**Issue by h0vhannes** [interledgerjs/ilp-kit#449]
User A sends money to user B using five bells ledger plugin and SPSP (the example code in ilp client repo - https://github.com/interledgerjs/ilp/blob/master/README.md#simple-payment-setup-protocol-spsp). 

User B's wallet is being updated and user B sees the incoming transfer.
User A doesn't see any updates in her wallet.

**Comment by vhpoet** [comment]
Yep, we're aware of this. Payments not sent from the ILP Kit are not shown for the sender atm.
