### ISSUE TITLE
tests fail in node 8

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#458]
[This rollback to node 7](https://github.com/interledgerjs/ilp-kit/commit/425504521467710e53424b2806f9bc8ee7812280) was necessary to make the tests pass on [this branch](https://circleci.com/gh/interledgerjs/ilp-kit/tree/mj-node-8). The test that fails is in the "connector_first" suite.

cc @sentientwaffle, you said you already reproduced this problem locally? You could try running with NODE_PENDING_DEPRECATION=1, see https://nodejs.org/en/blog/release/v8.0.0/#buffer-changes

**Comment by sentientwaffle** [comment]
Fixed: https://github.com/interledgerjs/ilp-kit/pull/459
