### ISSUE TITLE
api docs incorrect?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#460]
It seems https://interledgerjs.github.io/ilp-kit/apidoc/#api-User-GetUser is incorrect, looking into that. At least, the URL should be /api/users instead of /users, but it only seems to work for the currently logged in user, according to the docs, the admin should be able to get any user's details with that API call. Example:

```sh
node
> Buffer.from('admin:iequae9hadoo7ohz4Teequ2uod5Ifei3Oiz4iev2', 'ascii').toString('base64')
'YWRtaW46aWVxdWFlOWhhZG9vN29oejRUZWVxdTJ1b2Q1SWZlaTNPaXo0aWV2Mg=='
> Buffer.from('alice:alice', 'ascii').toString('base64')
'YWxpY2U6YWxpY2U='
>
(To exit, press ^C again or type .exit)
>
[michiel@mbp ~]$ curl -X GET -H "Authorization: Basic YWRtaW46aWVxdWFlOWhhZG9vN29oejRUZWVxdTJ1b2Q1SWZlaTNPaXo0aWV2Mg==" https://ilp-kit-master.herokuapp.com/api/users/alice
Not Found[michiel@mbp ~]$
[michiel@mbp ~]$ curl -X GET -H "Authorization: Basic YWxpY2U6YWxpY2U=" https://ilp-kit-master.herokuapp.com/api/users/alice
{"id":3,"username":"alice","email":"alice@yes.com","email_verified":null,"github_id":null,"destination":"940248","profile_picture":null,"name":null,"phone":null,"address1":null,"address2":null,"city":null,"region":null,"country":null,"zip_code":null,"invite_code":"10fc3320-55b5-43ea-88c9-e0b4fc903f13","identifier":"alice@ilp-kit-master.herokuapp.com","balance":10,"minimum_allowed_balance":"0"}[michiel@mbp ~]$
[michiel@mbp ~]$

**Comment by michielbdejong** [comment]
This is fixed by #461, I deployed that branch to ilp-kit-master.herokuapp.com and `curl -X GET -H "Authorization: Basic YWRtaW46aWVxdWFlOWhhZG9vN29oejRUZWVxdTJ1b2Q1SWZlaTNPaXo0aWV2Mg==" https://ilp-kit-master.herokuapp.com/api/users/alice` works now.

**Comment by dappelt** [comment]
> according to the docs, the admin should be able to get any user's details with that API call.

If requested by the admin, `/api/users` returns a list of all users. So I think the docs are correct.

**Comment by vhpoet** [comment]
added `/api` prefixes in https://github.com/interledgerjs/ilp-kit/commit/7bf1e62c9831417967297f87c11ea8411fa88c36
