### ISSUE TITLE
Trustline balance is displayed as zero if a peer unpeers

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#462]
The trustline balance is displayed as zero after a peer unpeers with you. Instead, it should display the current trustline balance.

Balance before:
![image](https://user-images.githubusercontent.com/23212287/28962842-4ff4a836-7907-11e7-8890-d68920683b3a.png)

Balance after wallet1 unpeers from wallet2, without any settlement payment performed:
![image](https://user-images.githubusercontent.com/23212287/28962870-61f76118-7907-11e7-812e-d128f74584f7.png)

(cc @vhpoet )

**Comment by michielbdejong** [comment]
Also if your peer is unreachable (which I guess is the same thing from your ilp-kit's perspective)
