### ISSUE TITLE
displaying destination currency before destination is entered is confusing

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#467]
As discussed with @manali103, it's confusing that it looks like ilp-kit can only do $ to $ payments.

I think it would be better to make it clearer that destination SPSP account will uniquely define the destination currency, and so it's not obvious at all that currency depends on you putting in that address first. Maybe hide the destination amount box at first, so that the user is forced to type an address before proceeding? Or at least add a hint saying 'will depend on the sender address'

**Comment by vhpoet** [comment]
fixed in c056707345c5d83a10d781ee26b1d660244f428c
