### ISSUE TITLE
chalk dependency

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#57]
when running _npm configure_:

_./node_modules/ilp-kit-cli/bin/configure.js -o env.list

module.js:327
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)_

**Comment by vhpoet** [comment]
@sharafian

**Comment by sharafian** [comment]
https://github.com/interledgerjs/ilp-kit-cli/commit/55f6d4633bc7936161009b8f3f5f1e24bf223910 fixed in `ilp-kit-cli` v4.0.8
