### ISSUE TITLE
Connector should start after the ledger

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-kit#59]
Right now, there's a 10 second delay in `package.json` to make the connector start up after the ledger. On lower-resource systems, the ledger will not be fully running after 10 seconds, causing the connector to get a `Could not get ledger URI from account URI` error. The delay has to be changed to 20 seconds on those systems.

We should change the way ilp-kit launches components to ensure that connector is always started after the ledger is up and running

**Comment by emschwartz** [comment]
We should fix the connector and ledger so that having the connector start before the ledger is not a problem. I think the connector should immediately try to connect to the ledger, retry until it can, and only facilitate payments once it is has successfully connected.

**Comment by vhpoet** [comment]
@emschwartz sounds like a github issue for `ilp-connector`.
