### ISSUE TITLE
Negative quote values shown for small sending payment amounts

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#63]
ie try to send $0.01

**Comment by vhpoet** [comment]
@peterjkrey how do I reproduce this? which kits are you using?

**Comment by peterjkrey** [comment]
reproduce by trying to send a very small amount ie $0.001

**Comment by vhpoet** [comment]
Can't reproduce. Is this an interledger payment or a local one? what's the fee on connectors?

**Comment by peterjkrey** [comment]
Appears to have been fixed - I just tested it.

**Comment by vhpoet** [comment]
Closing this for now, feel free to reopen if you notice it again.
