### ISSUE TITLE
Verification emails should include ilp-kit name / domain

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#67]
Right now you see the very generic:

![image](https://cloud.githubusercontent.com/assets/3262610/20328262/eaac4544-ab91-11e6-89ca-3bcbaff2933a.png)

**Comment by vhpoet** [comment]
@emschwartz you can specify `CLIENT_TITLE`, `API_EMAIL_SENDER_NAME` and `API_EMAIL_SENDER_ADDRESS` env vars.
