### ISSUE TITLE
Get transfer URL from history view

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#74]
In earlier iterations there was a way to expand the transfer to see the JSON details. I don't think we need to bring that back but it would be nice to have some way of getting the transfer URL to fetch the full details in your browser.

**Comment by vhpoet** [comment]
Which transfer? the local one?

**Comment by emschwartz** [comment]
Yes the local one. It doesn't have to be a super prominent feature but it's
useful for debugging and some tracing
