### ISSUE TITLE
Register with Github redirects broken

### ISSUE THREAD

**Issue by adrianhopebailie** [interledgerjs/ilp-kit#75]
Attempting to register using Github at nexus.justmoon.com sent me to http://ww25.wallet1.com/legacy

@justmoon: May be a config issue?

**Comment by vhpoet** [comment]
just looked at the code, doesn't seem like there's any hardcode. This is probably a config thing. @justmoon please confirm and close this.

**Comment by justmoon** [comment]
Yeah, config issue.
