### ISSUE TITLE
RegisterForm: How to disable invite codes?

### ISSUE THREAD

**Issue by diminator** [interledgerjs/ilp-kit#79]
Registering a user is a bit tedious:
- the register tab only pops up after clicking a few times on the `login` tab
- registration requires an invite code of type `<UUID>`. I'd like to disable this for testing

see http://ec2-35-156-124-159.eu-central-1.compute.amazonaws.com:3010/login

**Comment by vhpoet** [comment]
@diminator do you want to disable the `uuid` check or the invite feature altogether?

**Comment by vhpoet** [comment]
@diminator both problems should be fixed. The registration should only require an invite code when the `API_REGISTRATION` env var is `false`.
