### ISSUE TITLE
Setup help - issuing command

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#82]
Minor typo:

In https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md#issue-some-money the balance should not  be zero?

curl -H 'Content-Type: application/json' -X PUT https://niles.sharafian.com/ledger/accounts/issuer --user admin:PASSWORD -d '{"minimum_allowed_balance":"-infinity","balance":"**0**","is_disabled":false, "id":"https://niles.sharafian.com/ledger/accounts/issuer","name":"issuer"}'

**Comment by sharafian** [comment]
The balance is never changed by manually setting it. That command sets `"minimum_allowed_balance":"-infinity"`, which allows the issuer account to go infinitely negative and give money to other accounts.

This ensures that no money is ever created or destroyed on the ledger (all balances must sum to 0).

**Comment by elmurci** [comment]
Thanks, makes sense.
The API shouldn't allow the balance to be changed manually then?

**Comment by sharafian** [comment]
Filed an issue on ledger.

**Comment by vhpoet** [comment]
https://github.com/interledgerjs/five-bells-ledger/issues/370
