### ISSUE TITLE
Connector exits with `auth_token` ExternalError

### ISSUE THREAD

**Issue by diminator** [interledgerjs/ilp-kit#83]
Ledger and API seem to be running fine on https://ilp.bigchaindb.com
I have an account on dimitri@zar-ilp.hopebailie.com with liquidity and a user dimitri on https://ilp.bigchaindb.com with liquidity

the error stack

```
[connector] 2016-11-22T22:14:35.313Z connector:app info pair [ 'ZAR@za.zar.hopebailie.', 'EUR@de.eur.berlin.' ]
[connector] 2016-11-22T22:14:35.318Z connector:app info pair [ 'EUR@de.eur.berlin.', 'ZAR@za.zar.hopebailie.' ]
[connector] 2016-11-22T22:14:35.427Z connector:subscriptions info subscribing to za.zar.hopebailie.
[connector] 2016-11-22T22:14:35.429Z connector:subscriptions info subscribing to de.eur.berlin.
[connector] 2016-11-22T22:14:35.489Z connector:app error ExternalError: ledger metadata does not include auth_token url
[connector]     at REQUIRED_LEDGER_URLS.forEach (/home/ubuntu/ilp-kit/node_modules/ilp-connector/node_modules/ilp-plugin-bells/src/lib/plugin.js:818:13)
[connector]     at Array.forEach (native)
[connector]     at parseAndValidateLedgerUrls (/home/ubuntu/ilp-kit/node_modules/ilp-connector/node_modules/ilp-plugin-bells/src/lib/plugin.js:816:24)
[connector]     at FiveBellsLedger._connect (/home/ubuntu/ilp-kit/node_modules/ilp-connector/node_modules/ilp-plugin-bells/src/lib/plugin.js:180:17)
[connector]     at next (native)
[connector]     at onFulfilled (/home/ubuntu/ilp-kit/node_modules/co/index.js:65:19)
[connector]     at process._tickCallback (internal/process/next_tick.js:103:7)
[connector] npm run start-prod-connector exited with code 0
```

the `env.list`

```
API_DB_URI=postgres://<user>:<password>@localhost/ilpkit
API_GITHUB_CLIENT_ID=
API_GITHUB_CLIENT_SECRET=
API_HOSTNAME=ilp.bigchaindb.com
API_MAILGUN_API_KEY=
API_MAILGUN_DOMAIN=
API_PORT=3100
API_PRIVATE_HOSTNAME=localhost
API_PUBLIC_HTTPS=1
API_PUBLIC_PATH=/api
API_PUBLIC_PORT=443
API_SECRET=<secret>
BLUEBIRD_WARNINGS=0
CLIENT_HOST=ilp.bigchaindb.com
CLIENT_PORT=3010
CLIENT_PUBLIC_PORT=443
CLIENT_TITLE=ILP greetings from BigchainDB in Berlin
LEDGER_ADMIN_USER=admin
LEDGER_ADMIN_PASS=<admin>
LEDGER_CURRENCY_CODE=EUR
LEDGER_CURRENCY_SYMBOL=€
LEDGER_ILP_PREFIX=de.eur.berlin.
LEDGER_RECOMMENDED_CONNECTORS=dimitri
CONNECTOR_ENABLE=true
CONNECTOR_LEDGERS={"za.zar.hopebailie.":{"plugin":"ilp-plugin-bells","currency":"ZAR","options":{"identifier":"dimitri@zar-ilp.hopebailie.com","password":<secret>}},"de.eur.berlin.":{"currency":"EUR","plugin":"ilp-plugin-
bells","options":{"account":"https://ilp.bigchaindb.com/ledger/accounts/dimitri","password":<secret>}}}
CONNECTOR_LOG_LEVEL=info
CONNECTOR_MAX_HOLD_TIME=100
CONNECTOR_PEERS=za.zar.hopebailie.adrian
CONNECTOR_PORT=4000
```

**EDIT**

logging `metadataUrls` in `ilp-plugin-bells/src/lib/plugin.js:parseAndValidateLedgerUrls`
```
[api] { health: 'https://ilp.bigchaindb.com/ledger/health',
[api]   transfer: 'https://ilp.bigchaindb.com/ledger/transfers/:id',
[api]   transfer_fulfillment: 'https://ilp.bigchaindb.com/ledger/transfers/:id/fulfillment',
[api]   transfer_rejection: 'https://ilp.bigchaindb.com/ledger/transfers/:id/rejection',
[api]   transfer_state: 'https://ilp.bigchaindb.com/ledger/transfers/:id/state',
[api]   accounts: 'https://ilp.bigchaindb.com/ledger/accounts',
[api]   account: 'https://ilp.bigchaindb.com/ledger/accounts/:name',
[api]   account_transfers: 'wss://ilp.bigchaindb.com/ledger/accounts/:name/transfers',
[api]   message: 'https://ilp.bigchaindb.com/ledger/messages' }
```

seems not to contain some of the required `REQUIRED_LEDGER_URLS`
`[ 'transfer', 'transfer_fulfillment', 'transfer_rejection', 'account', 'auth_token', 'websocket', 'message' ]`

npm (package) versions
```
  npm: '3.10.8',
  node: '6.9.1',

ilp-kit@1.0.0 /home/ubuntu/ilp-kit
├─┬ ilp-connector@12.2.2
│ └── ilp-plugin-bells@9.0.0 
├── ilp-plugin-bells@8.3.0 
├─┬ five-bells-ledger@18.0.1 
```

**Comment by diminator** [comment]
fixing `ilp-connector@12.2.0` resolves the issue and allows me to make a payment

For a payment from dimitri@ilp.bigchaindb.com to dimitri@zar-ilp.hopebaillie.com:
- filling in `source_amount` yields: `Woops! Couldn't find a quote for the specified recipient or amount`, but `destination_amount` returns a quote
- the payment then goes through, messaging as successful
- **shows in the history** of the received ledger: dimitri@zar-ilp.hopebaillie.com
- **does not show** in the history of the sending ledger: dimitri@ilp.bigchaindb.com
- the balances on both ledgers **remain the initial balances**

For an inverse payment from dimitri@zar-ilp.hopebaillie.com to dimitri@ilp.bigchaindb.com:
- filling in `source_amount` **and** `destination_amount`yields: `Woops! Couldn't find a quote for the specified recipient or amount`,

**Comment by sentientwaffle** [comment]
`ilp-plugin-bells@9.0.0` (and by extension `ilp-connector@12.2.2`) requires `five-bells-ledger@19.0.0` due to changes to the websocket API.

**Comment by diminator** [comment]
thanks for the response

still getting the  error
```2016-11-24T14:56:14.660Z connector:app error ExternalError: ledger metadata does not include auth_token url```

using the master branch
Maybe due to the installation on `zar-ilp.hopebailie.com`
do you have an alternative ledger (with latest changes) I can try to connect to?

**Comment by vhpoet** [comment]
@diminator can you try now?

**Comment by misnuge** [comment]
Just to let you know that 117th line of db.js(ilp-kit/node_modules/five-bells-ledger/src/lib/db.js) should be modified like below.


const command = path.resolve(__dirname, '../../node_modules/pg-migrator/bin/pg-migrator')


If not, db schema will not be applied.


________________________________
보낸 사람: Vahe Hovhannisyan <notifications@github.com>
보낸 날짜: 2016년 11월 30일 수요일 오전 6:28:13
받는 사람: interledgerjs/ilp-kit
제목: Re: [interledgerjs/ilp-kit] Connector exits with `auth_token` ExternalError (#83)


@diminator<https://github.com/diminator> can you try now?

-

**Comment by vhpoet** [comment]
@misnuge that's fixed in the latest ledger version.
