### ISSUE TITLE
Fix apidoc

### ISSUE THREAD

**Issue by vhpoet** [interledgerjs/ilp-kit#90]
https://interledger.org/ilp-kit/apidoc

**Comment by vhpoet** [comment]
Fixed in the new address https://interledgerjs.github.io/ilp-kit/apidoc/

**Comment by Winthan** [comment]
please update https://interledger.org/ilp-kit/apidoc to https://interledgerjs.github.io/ilp-kit/apidoc/
at Description. 
Everything needed to create a ledger and connect it to the Interledger https://interledger.org/ilp-kit/apidoc

**Comment by vhpoet** [comment]
@Winthan thanks, updated.
