### ISSUE TITLE
UI should prominently show your [name]@[hostname] identifier

### ISSUE THREAD

**Issue by justmoon** [interledgerjs/ilp-kit#93]
If I want to send money to you, I need your `vahe@shady-ledger.example` webfinger identifier. But it's currently not obvious to the recipient what identifier they are supposed to provide.

Note that in the future the webfinger hostname might differ from the ILP Kit hostname. E.g. my ILP Kit might be at `nexus.justmoon.com`, but my webfinger is just `justmoon.com`. But for now, I'm happy if we want to assume that they're the same.

Also note that this identifier might also be used as a login credential when using the [ilp](https://github.com/interledgerjs/ilp) module, e.g.:

``` js
const sender = ILP.createSender({
  account: 'alice@red.ilpdemo.org',
  password: 'alice'
})
```

**Comment by vhpoet** [comment]
This is already implemented.
