### ISSUE TITLE
Cannot read property registration of null

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-kit#97]
Starting the ILP Kit on version `af71e9e5d7fcaaf2f2aadbbc020bf2ab7df98c84`, on the login page nothing happens when credentials are entered or any of the buttons are hit.

On hitting any control, a `MIDDLEWARE ERROR: TypeError: Cannot read property 'registration' of null` is emitted in the browser console, but nothing shows up on the ILP Kit log on the server

**Comment by vhpoet** [comment]
@sharafian looked at the code and I can't see why would this happen. Does this happen all the time?

**Comment by elmurci** [comment]
I am having the same issue in https://milton.ilp.network
This is what I see on start up:

[ledger] 2016-12-05T19:34:11.335Z ledger:koa info <-- GET /auth_token
[ledger] 2016-12-05T19:34:11.351Z ledger:error-handler warn Unauthorized: Invalid password
[ledger] 2016-12-05T19:34:11.352Z ledger:koa info --> GET /auth_token 403 17ms 55B
[connector] 2016-12-05T19:34:11.356Z connector:app error Error: Unable to get auth token from ledger
[connector]     at FiveBellsLedger._connect (/home/javi/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:210:27)
[connector]     at next (native)
[connector]     at onFulfilled (/home/javi/ilp-kit/node_modules/co/index.js:65:19)
[connector]     at process._tickCallback (internal/process/next_tick.js:103:7)
[ledger] 2016-12-05T19:34:17.129Z ledger:koa info <-- GET /accounts/admin
[ledger] 2016-12-05T19:34:17.139Z ledger:koa info --> GET /accounts/admin 200 10ms 117B
[ledger] 2016-12-05T19:34:17.156Z ledger:koa info <-- GET /
[ledger] 2016-12-05T19:34:17.160Z ledger:koa info --> GET / 200 4ms 911B
[ledger] 2016-12-05T19:34:17.198Z ledger:koa info <-- GET /auth_token
[ledger] 2016-12-05T19:34:17.220Z ledger:koa info --> GET /auth_token 200 22ms 272B
[ledger] 2016-12-05T19:34:17.247Z ledger:koa info <-- GET /websocket?token=xxx
[ledger] 2016-12-05T19:34:17.287Z ledger:rpcHandler info new ws subscriber for notification:admin:*

**Comment by elmurci** [comment]
after creating a new db as suggested in #98 it works fine...

**Comment by sharafian** [comment]
Same on my ILP Kit. I think we should have a SQL or bash script, to move data over after this change. I had to `pg_dump` my users, wrap the resulting SQL script in `BEGIN;` and `COMMIT;`, and then fix all the errors by hand when evaluating the script.

**Comment by vhpoet** [comment]
@sharafian will definitely try to make transition less painful next time something like this happens.
