### ISSUE TITLE
SequelizeDatabaseError: type "enum_Payments_state" already exists

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#98]
[api] 2016-12-05T19:25:26.583Z sequelize DEBUG Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id"  SERIAL , "username" VARCHAR(255) UNIQUE, "account" VARCHAR(255) UNIQUE, "email" VARCHAR(255) UNIQUE, "email_verified" BOOLEAN, "github_id" INTEGER UNIQUE, "profile_picture" VARCHAR(255), "name" VARCHAR(255), "phone" VARCHAR(255), "address1" VARCHAR(255), "address2" VARCHAR(255), "city" VARCHAR(255), "region" VARCHAR(255), "country" VARCHAR(255), "zip_code" VARCHAR(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("username"), UNIQUE ("account"), UNIQUE ("email"), UNIQUE ("github_id"), PRIMARY KEY ("id"))
[api] 2016-12-05T19:25:26.586Z sequelize DEBUG Executing (default): CREATE TYPE "public"."enum_Payments_state" AS ENUM('pending', 'success', 'fail')
[api] 2016-12-05T19:25:26.590Z app CRIT { SequelizeDatabaseError: type "enum_Payments_state" already exists
[api]     at Query.formatError (/home/javi/ilp-kit/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
[api]     at Query.<anonymous> (/home/javi/ilp-kit/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
[api]     at emitOne (events.js:96:13)
[api]     at Query.emit (events.js:188:7)
[api]     at Query.handleError (/home/javi/ilp-kit/node_modules/pg/lib/query.js:108:8)
[api]     at Connection.<anonymous> (/home/javi/ilp-kit/node_modules/pg/lib/client.js:171:26)
[api]     at emitOne (events.js:96:13)
[api]     at Connection.emit (events.js:188:7)
[api]     at Socket.<anonymous> (/home/javi/ilp-kit/node_modules/pg/lib/connection.js:109:12)
[api]     at emitOne (events.js:96:13)
[api]     at Socket.emit (events.js:188:7)

**Comment by vhpoet** [comment]
@elmurci yea, we switched `db.sync` with migrations, so please run the kit on a fresh new database.

**Comment by elmurci** [comment]
So, doing that solves the error, but anyone doing it will lose all the data?

**Comment by vhpoet** [comment]
@elmurci yea, you should move the data from the old db. This is due to db.sync -> migrations switch, this kind of a thing should never happen again.
