### ISSUE TITLE
admin issuance

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#99]
When you try to send payments from the **admin** account (with balance 0):

The front end shows the payment as successful (confirmation box) but you get this in the logs:

[ledger] 2016-12-07T13:08:49.257Z ledger:error-handler warn Insufficient Funds: Sender has insufficient funds.
[ledger] 2016-12-07T13:08:49.258Z ledger:koa info --> PUT /transfers/70b0ee59-b5e8-49d1-8695-71bd1b0e2e8f 422 56ms 90B
[api] 2016-12-07T13:08:49.261Z error-handler ERROR { NotAcceptedError: Sender has insufficient funds.
[api]     at NotAcceptedError (/home/javi/ilp-kit/node_modules/ilp-plugin-bells/src/errors/index.js:26:5)
[api]     at FiveBellsLedger._sendTransfer (/home/javi/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:504:13)
[api]     at next (native)
[api]     at onFulfilled (/home/javi/ilp-kit/node_modules/co/index.js:65:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by dappelt** [comment]
Confirmed, I followed the [instructions](https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md) to setup an ILP kit and was running into the same issue.

**Comment by vhpoet** [comment]
I experienced this as well yesterday. A quick fix would be to update the database "L_ACCOUNTS" table and set admin balance to `null`.

**Comment by vhpoet** [comment]
@elmurci @dappelt should be fixed.
